import { ArrowRight, BarChart3, BriefcaseBusiness, CheckCircle2, FileText, Mail, ScanSearch, WandSparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import { productFeatures } from './marketingData'

const icons = [FileText, Mail, ScanSearch, WandSparkles, BriefcaseBusiness]
export function FeatureOverview() { return <section className="marketing-section" id="fonctionnalites"><div className="page-width"><div className="marketing-heading"><div><p className="home-eyebrow"><span /> Une recherche mieux organisée</p><h2>Tout ce qu’il faut pour préparer une candidature avec soin.</h2></div><Link className="home-inline-link" to="/fonctionnalites">Découvrir <ArrowRight size={16} /></Link></div><div className="marketing-feature-grid">{productFeatures.map(([title, text], index) => { const Icon = icons[index]; return <article key={title}><span><Icon size={20} /></span><h3>{title}</h3><p>{text}</p><Link to="/fonctionnalites">Découvrir</Link></article> })}</div></div></section> }
export function JourneySection() { const steps = ['Créez votre CV', 'Analysez une offre', 'Adaptez votre candidature', 'Générez votre lettre', 'Suivez votre candidature']; return <section className="marketing-section marketing-section--tint"><div className="page-width"><p className="home-eyebrow"><span /> Un parcours cohérent</p><h2>De l’offre à la candidature, tout au même endroit.</h2><ol className="journey-steps">{steps.map((step, index) => <li key={step}><span>{index + 1}</span><b>{step}</b><p>{index === 0 ? 'Posez une base solide.' : index === 1 ? 'Comprenez les attentes.' : index === 2 ? 'Valorisez votre parcours.' : index === 3 ? 'Gardez la main sur votre texte.' : 'Restez organisé.'}</p></li>)}</ol></div></section> }
export function AnalysisSection() { return <section className="marketing-section"><div className="page-width analysis-marketing"><div><p className="home-eyebrow"><span /> Une lecture plus claire</p><h2>Voyez ce qui correspond à l’offre et ce qui mérite d’être renforcé.</h2><p>Novyata compare votre CV à une offre et vous aide à formuler des améliorations cohérentes, sans modifier votre document original.</p><Link className="home-inline-link" to="/fonctionnalites">Découvrir l’analyse d’offre <ArrowRight size={16} /></Link></div><aside className="analysis-demo" aria-label="Aperçu d’une analyse d’offre"><header><BarChart3 size={18} /><span>Correspondance</span><strong>78 %</strong></header><section><b>Correspondances fortes</b><p><CheckCircle2 size={14} /> Recherche utilisateur</p><p><CheckCircle2 size={14} /> Design system</p></section><section><b>À renforcer</b><p>Préciser vos usages de Figma</p><p>Ajouter des exemples de collaboration</p></section></aside></div></section> }
export function ApplicationsSection() { return <section className="marketing-section marketing-section--tint"><div className="page-width applications-marketing"><aside className="application-demo"><header><b>Mes candidatures</b><small>12 en cours</small></header>{[['Atelier Produit', 'Entretien'], ['Maison Studio', 'Candidature envoyée'], ['Pollen', 'À postuler']].map(([company, status]) => <div key={company}><span>{company.slice(0, 1)}</span><b>{company}</b><small>{status}</small></div>)}</aside><div><p className="home-eyebrow"><span /> Vos démarches en vue</p><h2>Suivez chaque candidature sans perdre le fil.</h2><p>Centralisez le statut, les documents associés et vos notes utiles : à postuler, envoyée, entretien, proposition ou refusée.</p><Link className="home-inline-link" to="/fonctionnalites">Découvrir le suivi <ArrowRight size={16} /></Link></div></div></section> }
