import { Check, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useAuth } from '../../store/AuthContext'

const plans = [
  { name: 'Novyata Free', label: 'Créez et organisez votre recherche.', items: ['CV, modèles et export PDF', 'Lettres de motivation manuelles', 'Suivi des candidatures', '5 analyses, 3 lettres IA et 3 adaptations / mois'] },
  { name: 'Novyata Pro', label: 'Adaptez chaque candidature plus rapidement.', pro: true, items: ['Tout Novyata Free', 'Plus d’analyses et de générations', 'Adaptation de CV par offre', 'Historique complet des analyses'] },
]
export default function PricingPreview({ full = false }) { const { isAuthenticated, user } = useAuth(); const isPro = user?.plan === 'pro'; const cta = isAuthenticated ? '/dashboard' : '/inscription'; return <section className={'marketing-section pricing-preview' + (full ? ' pricing-preview--full' : '')}><div className="page-width"><div className="marketing-heading"><div><p className="home-eyebrow"><span /> Des plans simples</p><h2>{full ? 'Un plan simple pour avancer à votre rythme.' : 'Commencez gratuitement. Passez à Pro quand vous avez besoin de plus.'}</h2><p>Le plan Pro met l’accent sur le temps gagné et la personnalisation de chaque candidature.</p></div>{!full && <Link to="/tarifs" className="home-inline-link">Voir les tarifs</Link>}</div><div className="pricing-grid">{plans.map((plan) => <article className={'pricing-card' + (plan.pro ? ' pricing-card--pro' : '')} key={plan.name}>{plan.pro && <span className="pricing-badge"><Sparkles size={13} /> Le plus complet</span>}<p>{plan.pro ? 'Pour accélérer' : 'Pour commencer'}</p><h3>{plan.name}</h3><strong>{plan.label}</strong>{plan.pro && <small className="pricing-price">Tarif mensuel configuré sur Stripe</small>}<ul>{plan.items.map((item) => <li key={item}><Check size={16} />{item}</li>)}</ul>{plan.pro && isPro ? <><span className="pricing-current-plan">Plan actuel : Novyata Pro</span><Link className="button button--primary" to="/parametres">Gérer mon abonnement</Link></> : <Link className={'button button--' + (plan.pro ? 'primary' : 'secondary')} to={plan.pro ? (isAuthenticated ? '/parametres' : '/inscription') : cta}>{plan.pro ? 'Passer à Pro' : 'Créer mon CV gratuitement'}</Link>}</article>)}</div></div></section> }
