import { expect, test } from '@playwright/test'
import { authenticatedPage, mockApi } from './fixtures.js'

test('authentification : inscription, dashboard, déconnexion et route privée', async ({ page }) => {
  await mockApi(page)
  await page.goto('/dashboard')
  await expect(page).toHaveURL(/\/connexion$/)
  await page.goto('/inscription')
  await page.getByLabel('Prénom').fill('Élise')
  await page.getByLabel('Nom', { exact: true }).fill('Durand')
  await page.getByLabel('Adresse e-mail').fill('elise.e2e@example.test')
  await page.locator('input[name="password"]').fill('password-e2e')
  await page.getByLabel('Confirmer le mot de passe').fill('password-e2e')
  await page.getByRole('button', { name: 'Créer mon compte' }).click()
  await expect(page).toHaveURL(/\/dashboard$/)
  await expect(page.getByRole('heading', { name: "Vue d'ensemble" })).toBeVisible()
  await page.getByRole('button', { name: 'Déconnexion' }).click()
  await expect(page).toHaveURL(/\/connexion$/)
})

test('profil de recherche : sauvegarde et restauration après actualisation', async ({ page }) => {
  await authenticatedPage(page)
  await page.goto('/parametres')
  await page.getByLabel('Métiers recherchés').fill('Data Analyst, BI Analyst')
  await page.getByLabel('Localisation souhaitée').fill('Lyon')
  await page.getByLabel('Télétravail').fill('Hybride')
  await page.getByRole('button', { name: 'Enregistrer ma recherche' }).click()
  await expect(page.getByRole('status')).toContainText('Modifications enregistrées.')
  await page.reload()
  await expect(page.getByLabel('Métiers recherchés')).toHaveValue('Data Analyst, BI Analyst')
  await expect(page.getByLabel('Localisation souhaitée')).toHaveValue('Lyon')
  await expect(page.getByLabel('Télétravail')).toHaveValue('Hybride')
})

test('portfolio : reste privé par défaut et publie uniquement les rubriques choisies', async ({ page }) => {
  const state = await authenticatedPage(page)
  await page.goto('/portfolio')
  await expect(page.getByLabel('Publier mon portfolio')).not.toBeChecked()
  await page.getByLabel('Nom').check()
  await page.getByLabel('Poste recherché').check()
  await page.getByLabel('Expériences').check()
  await page.getByLabel('Publier mon portfolio').check()
  await page.getByRole('button', { name: 'Enregistrer les réglages' }).click()
  await expect(page.getByRole('link', { name: /Aperçu public/ })).toBeVisible()
  expect(state.publicProfile.visible_sections).toMatchObject({ name: true, job_title: true, experiences: true, skills: false })
  await page.goto('/p/elise-durand')
  await expect(page.getByRole('heading', { name: 'Élise Durand' })).toBeVisible()
  await expect(page.getByText(/@/)).toHaveCount(0)
  expect(state.publicProfile.is_published).toBe(true)
})

test('objectifs hebdomadaires : activation, progression descriptive et désactivation', async ({ page }) => {
  const state = await authenticatedPage(page)
  state.applications.push({ id_application: 'aa8dc2f2-6ff2-43d2-9e4f-5443200f6d4b', company_name: 'CloudNova' })
  await page.goto('/dashboard')
  await page.getByLabel('Activer mes objectifs hebdomadaires').check()
  await page.getByRole('button', { name: 'Enregistrer mes objectifs' }).click()
  await expect(page.getByText('1 / 5')).toBeVisible()
  expect(state.weeklyGoal.is_enabled).toBe(true)
  await page.getByLabel('Activer mes objectifs hebdomadaires').uncheck()
  await page.getByRole('button', { name: 'Enregistrer mes objectifs' }).click()
  expect(state.weeklyGoal.is_enabled).toBe(false)
})

test('partage CV : lien non prédictible, coordonnées privées par défaut et révocation effective', async ({ page }) => {
  const state = await authenticatedPage(page)
  await page.goto(`/cv/${state.resume.id_resume}`)
  await page.getByLabel('Expiration').selectOption('7')
  await page.getByRole('button', { name: 'Créer un lien de partage' }).click()
  await expect(page.getByRole('link', { name: 'Ouvrir le lien de partage' })).toBeVisible()
  const sharePath = state.resumeShareLinks[0].path
  expect(sharePath).toMatch(/^\/cv\/share\/[A-Za-z0-9_-]{43}$/)
  expect(state.resumeShareLinks[0].include_contact_details).toBe(false)
  await page.goto(sharePath)
  await expect(page.getByText('CV partagé en privé')).toBeVisible()
  await expect(page.getByText('Élise', { exact: true })).toHaveCount(0)
  await expect(page.getByText('elise.e2e@example.test')).toHaveCount(0)
  await page.goto(`/cv/${state.resume.id_resume}`)
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Révoquer le lien' }).click()
  await expect(page.getByText('Lien révoqué')).toBeVisible()
  await page.goto(sharePath)
  await expect(page.getByRole('heading', { name: 'Ce lien n’est plus disponible' })).toBeVisible()
})

test('centre de notifications : rappel lié à une candidature, lecture et archivage', async ({ page }) => {
  const state = await authenticatedPage(page)
  await page.setViewportSize({ width: 320, height: 780 })
  state.applications.push({ id_application: 'aa8dc2f2-6ff2-43d2-9e4f-5443200f6d4b', company_name: 'CloudNova', job_title: 'Product Designer', status: 'Candidature envoyée' })
  state.notifications.push({ id_notification: 'notification-e2e', id_application: 'aa8dc2f2-6ff2-43d2-9e4f-5443200f6d4b', type: 'no_response', title: 'Une relance est possible', body: 'Aucune réponse de CloudNova depuis 8 jours.', scheduled_for: '2026-10-02T10:00:00.000Z', is_read: false })
  await page.goto('/notifications')
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await expect(page.getByText('Une relance est possible')).toBeVisible()
  await expect(page.getByRole('link', { name: 'Ouvrir la candidature' })).toHaveAttribute('href', '/candidatures/aa8dc2f2-6ff2-43d2-9e4f-5443200f6d4b')
  await page.getByRole('button', { name: 'Marquer comme lu', exact: true }).click()
  await expect(page.getByRole('link', { name: 'Notifications' })).toBeVisible()
  await page.getByRole('button', { name: 'Archiver la notification' }).click()
  await expect(page.getByText('Vous êtes à jour')).toBeVisible()
  expect(state.notifications[0].is_read).toBe(true)
  expect(state.notifications[0].archived_at).toBeTruthy()
  await page.getByText('Programmer une prochaine action').click()
  await page.getByLabel('Candidature').selectOption('aa8dc2f2-6ff2-43d2-9e4f-5443200f6d4b')
  await page.getByLabel('Action à ne pas oublier').fill('Préparer mon prochain échange')
  await page.getByLabel('Date et heure').fill('2027-01-01T10:00')
  await page.getByRole('button', { name: 'Programmer le rappel' }).click()
  await expect(page.getByText('Préparer mon prochain échange')).toBeVisible()
  expect(state.notifications.some((item) => item.type === 'next_action')).toBe(true)
})

test('import CV : vérification manuelle avant création', async ({ page }) => {
  const state = await authenticatedPage(page)
  await page.setViewportSize({ width: 320, height: 780 })
  await page.goto('/cv')
  await page.getByRole('link', { name: 'Importer un CV' }).click()
  await page.locator('#resume-import-file').setInputFiles({ name: 'cv-elise.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-test') })
  await page.getByRole('button', { name: 'Analyser le fichier' }).click()
  await expect(page.getByRole('heading', { name: 'Relisez les informations extraites' })).toBeVisible()
  await expect(page.getByText(/À vérifier : expériences/)).toBeVisible()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(state.importSaved).toBe(false)
  await page.getByLabel('Prénom').fill('Élise-Marie')
  await page.getByRole('button', { name: 'Créer mon CV à partir de cet import' }).click()
  await expect(page).toHaveURL(/\/cv\/import-e2e$/)
  expect(state.importSaved).toBe(true)
})

test('CV : création, personnalisation et réouverture', async ({ page }) => {
  await authenticatedPage(page)
  await page.goto('/cv/nouveau')
  await page.getByLabel('Titre du CV').fill('CV produit E2E')
  await page.getByLabel('Poste recherché').fill('Product Designer')
  await page.getByRole('button', { name: 'Créer mon CV' }).click()
  await expect(page).toHaveURL(/\/cv\//)
  await page.getByRole('button', { name: 'Ajouter une expérience' }).click()
  await page.getByRole('combobox').last().fill('Designer produit')
  await page.getByLabel('Entreprise').last().fill('Novyata')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).last().click()
  await page.getByRole('button', { name: 'Ajouter une formation' }).click()
  await page.getByLabel('Diplôme / Formation').fill('Master design')
  await page.getByLabel('Établissement').fill('École E2E')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).last().click()
  await page.getByLabel('Ajouter une compétence personnalisée').fill('Figma')
  await page.getByRole('button', { name: '+ Ajouter', exact: true }).click()
  await page.getByRole('button', { name: 'Utiliser ce modèle' }).first().click()
  await page.getByRole('button', { name: 'Grand' }).click()
  await page.getByLabel('Prénom').fill('Élise')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).first().click()
  await page.reload()
  await expect(page.getByText('CV produit E2E')).toBeVisible()
  await page.locator('.editor-actions').getByRole('button', { name: 'Supprimer', exact: true }).click()
  await page.getByRole('button', { name: 'Supprimer définitivement' }).click()
  await expect(page).toHaveURL(/\/dashboard$/)
})

test('Pro : comparer deux CV puis consulter et dupliquer une version sans remplacer l’original', async ({ page }) => {
  const state = await authenticatedPage(page)
  state.user.plan = 'pro'
  state.variant = { ...state.resume, id_resume: 'dd8dc2f2-6ff2-43d2-9e4f-5443200f6d4b', title_resume: 'CV Product Designer — Novyata', summary: 'Profil adapté à Novyata.', variants: [] }
  state.resumeVersions = [{ id_resume_version: 'version-e2e', version_label: 'Version enregistrée', reason: 'Résumé modifié', snapshot: {}, created_at: '2026-10-01T10:00:00.000Z' }]
  await page.goto('/cv')
  await page.getByRole('link', { name: 'Comparer deux CV' }).click()
  await expect(page).toHaveURL(/\/cv\/comparer$/)
  await page.getByRole('button', { name: 'Comparer' }).click()
  await expect(page.getByRole('heading', { name: 'CV Product Designer — Novyata' })).toBeVisible()
  await expect(page.getByText('Profil adapté à Novyata.')).toBeVisible()

  await page.goto(`/cv/${state.resume.id_resume}`)
  await page.getByText('Versions enregistrées').click()
  await expect(page.getByText(/Résumé modifié ·/)).toBeVisible()
  await page.getByRole('button', { name: /Dupliquer/ }).click()
  await expect(page).toHaveURL(/\/cv\/version-copy-e2e$/)
  await expect(page.getByText('CV E2E — Copie')).toBeVisible()
})

test('Free : les templates Pro sont visibles mais renvoient vers les tarifs', async ({ page }) => {
  await authenticatedPage(page)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/cv/f8c5d2f2-6ff2-43d2-9e4f-5443200f6d4b')
  await expect(page.getByText('Corporate', { exact: true }).first()).toBeVisible()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('link', { name: 'Débloquer avec Novyata Pro' }).first().click()
  await expect(page).toHaveURL(/\/tarifs$/)
})

test('éditeur CV : la proposition de résumé reste éditable et nécessite une validation et une sauvegarde', async ({ page }) => {
  const state = await authenticatedPage(page)
  await page.goto(`/cv/${state.resume.id_resume}`)
  await page.getByRole('button', { name: 'Générer un résumé' }).click()
  await expect(page.getByLabel('Résumé proposé')).toHaveValue(/Product Designer spécialisé/)
  await expect(page.getByLabel('Présentation')).toHaveValue('Profil de test.')
  await page.getByLabel('Résumé proposé').fill('Résumé relu et confirmé par Élise, basé sur son expérience produit.')
  await page.getByRole('button', { name: 'Utiliser cette proposition' }).click()
  await expect(page.getByLabel('Présentation')).toHaveValue('Résumé relu et confirmé par Élise, basé sur son expérience produit.')
  expect(state.resume.summary).toBe('Profil de test.')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).first().click()
  await expect(page.getByText('Modifications enregistrées.')).toBeVisible()
  expect(state.resume.summary).toBe('Résumé relu et confirmé par Élise, basé sur son expérience produit.')
})

test('éditeur CV : la reformulation d’expérience est une proposition et reste modifiable avant sauvegarde', async ({ page }) => {
  const state = await authenticatedPage(page)
  state.resume.experiences.push({ id_experience: 'experience-e2e', job_title: 'Analyste data', company: 'Studio Nova', description: 'Création de tableaux de bord.' })
  await page.goto(`/cv/${state.resume.id_resume}`)
  await page.getByRole('button', { name: 'Modifier Analyste data' }).click()
  await page.getByRole('button', { name: 'Améliorer la description' }).click()
  await expect(page.getByLabel('Texte proposé')).toHaveValue(/Conception de parcours utilisateurs/)
  await expect(page.getByRole('textbox', { name: 'Description' })).toHaveValue('Création de tableaux de bord.')
  await page.getByLabel('Texte proposé').fill('Reformulation vérifiée manuellement par Élise.')
  await page.getByRole('button', { name: 'Utiliser cette proposition' }).click()
  await expect(page.getByRole('textbox', { name: 'Description' })).toHaveValue('Reformulation vérifiée manuellement par Élise.')
  expect(state.resume.experiences[0].description).toBe('Création de tableaux de bord.')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).last().click()
  await expect.poll(() => state.resume.experiences[0].description).toBe('Reformulation vérifiée manuellement par Élise.')
})

test('éditeur CV : les compétences vues dans plusieurs expériences ne sont ajoutées qu’au choix de l’utilisateur', async ({ page }) => {
  const state = await authenticatedPage(page)
  state.resume.experiences.push({ id_experience: 'experience-e2e', job_title: 'Développeuse', company: 'Studio Nova', description: 'Développement avec React et composants React.' })
  await page.goto(`/cv/${state.resume.id_resume}`)
  const suggestion = page.getByText(/React apparaît 2 fois dans vos expériences/)
  await expect(suggestion).toBeVisible()
  await expect(page.getByText(/À ajouter uniquement si elles correspondent/)).toBeVisible()
  await page.getByRole('button', { name: 'Ajouter', exact: true }).click()
  await expect(page.getByText(/React apparaît 2 fois dans vos expériences/)).toHaveCount(0)
  expect(state.resume.skills.some((item) => item.name === 'React')).toBe(true)
})

test('Pro : sélection de template, section avancée, réorganisation, variante et export PDF', async ({ page }) => {
  test.setTimeout(90_000)
  const state = await authenticatedPage(page)
  state.user.plan = 'pro'
  await page.goto('/cv/f8c5d2f2-6ff2-43d2-9e4f-5443200f6d4b')
  const corporateCard = page.locator('.template-card').nth(3)
  await corporateCard.getByRole('button', { name: 'Utiliser ce modèle' }).click()
  const templateNames = ['Corporate', 'Élégant', 'Tech', 'Créatif sobre', 'Étudiant / Junior', 'Manager / Cadre']
  for (let index = 3; index < 9; index += 1) {
    const card = page.locator('.template-card').nth(index)
    if (index !== 3) await card.getByRole('button', { name: 'Utiliser ce modèle' }).click()
    await page.evaluate(() => new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve))))
    const paperMetrics = await page.getByRole('region', { name: 'Aperçu du CV' }).locator('.resume-preview-paper').evaluate((paper) => ({ clientHeight: paper.clientHeight, scrollHeight: paper.scrollHeight }))
    expect(paperMetrics.scrollHeight, `${templateNames[index - 3]} doit tenir dans son format A4`).toBeLessThanOrEqual(paperMetrics.clientHeight)
    const downloadPromise = page.waitForEvent('download')
    const downloadButton = page.getByRole('button', { name: 'Télécharger en PDF' })
    await expect(downloadButton).toBeEnabled()
    await downloadButton.click()
    expect((await downloadPromise).suggestedFilename()).toMatch(/\.pdf$/i)
  }
  await page.locator('.template-card').nth(3).getByRole('button', { name: 'Utiliser ce modèle' }).click()
  await page.getByRole('button', { name: 'Ajouter une section' }).click()
  await page.getByLabel('Titre').fill('Projets')
  await page.getByLabel('Contenu').fill('Prototype produit livré en équipe.')
  await page.getByRole('button', { name: 'Enregistrer la section' }).click()
  await expect(page.getByText('Projets', { exact: true }).first()).toBeVisible()
  const reorderResponsePromise = page.waitForResponse((response) => response.url().includes('/section-order'))
  await page.getByRole('button', { name: 'Descendre Profil' }).click()
  const reorderResponse = await reorderResponsePromise
  expect(reorderResponse.status()).toBe(200)
  expect(state.resume.section_order.slice(0, 2)).toEqual(['experiences', 'summary'])
  await page.getByLabel('Nom de la nouvelle variante').fill('Version Projets')
  await page.getByRole('button', { name: 'Créer une variante' }).click()
  await expect(page).toHaveURL(/\/cv\/variant-e2e$/)
  await expect(page.getByText('Prototype produit livré en équipe.').first()).toBeVisible()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Télécharger en PDF' }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toMatch(/\.pdf$/i)
  await page.goto('/historique')
  await expect(page.getByRole('heading', { name: 'Historique complet' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Novyata' })).toBeVisible()
  await page.goto('/dashboard')
  await expect(page.getByRole('heading', { name: 'Statistiques avancées' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Résultats observés par CV' })).toBeVisible()
})

test('Pro : éditeur, sélection de template et sections avancées utilisables sur mobile', async ({ page }) => {
  const state = await authenticatedPage(page)
  state.user.plan = 'pro'
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/cv/f8c5d2f2-6ff2-43d2-9e4f-5443200f6d4b')

  const techCard = page.locator('.template-card').nth(5)
  await techCard.getByRole('button', { name: 'Utiliser ce modèle' }).click()
  await expect(techCard).toHaveClass(/template-card--selected/)
  await expect(page.getByRole('button', { name: 'Télécharger en PDF' })).toBeEnabled()

  const paper = page.getByRole('region', { name: 'Aperçu du CV' }).locator('.resume-preview-paper')
  const dimensions = await paper.evaluate((element) => ({ width: element.offsetWidth, height: element.offsetHeight }))
  expect(dimensions.width / dimensions.height).toBeCloseTo(210 / 297, 2)

  await page.getByRole('button', { name: 'Ajouter une section' }).click()
  await page.getByLabel('Titre').fill('Projets mobiles')
  await page.getByLabel('Contenu').fill('Interface conçue et testée sur mobile.')
  await page.getByRole('button', { name: 'Enregistrer la section' }).click()
  await expect(page.getByText('Projets mobiles', { exact: true }).first()).toBeVisible()
  for (const width of [1280, 1024, 768, 390]) {
    await page.setViewportSize({ width, height: 844 })
    const viewport = await page.evaluate(() => ({ width: window.innerWidth, documentWidth: document.documentElement.scrollWidth }))
    expect(viewport.documentWidth, `Pas de scroll horizontal à ${width}px`).toBeLessThanOrEqual(viewport.width)
    const responsivePaper = await paper.evaluate((element) => ({ width: element.offsetWidth, height: element.offsetHeight }))
    expect(responsivePaper.width / responsivePaper.height).toBeCloseTo(210 / 297, 2)
  }
})

test('dépassement A4 : sauvegarde et export sont bloqués', async ({ page }) => {
  const state = await authenticatedPage(page)
  state.resume.summary = 'Contenu de test très long. '.repeat(800)
  await page.goto('/cv/f8c5d2f2-6ff2-43d2-9e4f-5443200f6d4b')
  await expect(page.getByRole('alert')).toContainText('dépasse une page A4')
  await expect(page.getByRole('button', { name: 'Télécharger en PDF' })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true }).first()).toBeDisabled()
})

test('lettres et candidatures : liaison, sauvegarde, statut et filtre', async ({ page }) => {
  await authenticatedPage(page)
  await page.goto('/lettres/nouvelle')
  await page.getByLabel('Titre interne').fill('Lettre Novyata')
  await page.getByLabel('CV associé').selectOption({ index: 1 })
  await page.getByLabel('Contenu').fill('Madame, Monsieur, je souhaite vous proposer ma candidature pour ce poste de Product Designer.')
  await page.getByRole('button', { name: 'Créer la lettre' }).click()
  await expect(page).toHaveURL(/\/lettres\//)
  await page.getByLabel('Objet').fill('Candidature Product Designer')
  await page.getByRole('button', { name: 'Enregistrer les modifications' }).click()
  await expect(page.getByText('Modifications enregistrées.')).toBeVisible()
  await page.goto('/candidatures/nouvelle')
  await page.getByLabel('Entreprise').fill('Novyata')
  await page.getByLabel('Poste').fill('Product Designer')
  await page.getByLabel('CV associé').selectOption({ index: 1 })
  await page.getByLabel('Lettre associée').selectOption({ index: 1 })
  await page.getByLabel('Statut').selectOption('Entretien')
  await page.getByRole('button', { name: 'Ajouter la candidature' }).click()
  await expect(page).toHaveURL(/\/candidatures\//)
  await page.goto('/candidatures')
  await expect(page.getByText('Novyata')).toBeVisible()
  await page.getByRole('combobox').nth(0).selectOption('Entretien')
  await expect(page.getByText('Product Designer')).toBeVisible()
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Supprimer Novyata' }).click()
  await expect(page.getByText('Vous n’avez encore aucune candidature.')).toBeVisible()
})

test('analyse d’offre : résultat, génération puis sauvegarde de lettre mockés', async ({ page }) => {
  await authenticatedPage(page)
  await page.goto('/analyse-offre')
  await page.getByLabel('CV à analyser').selectOption({ index: 1 })
  await page.getByLabel('Texte de l’offre').fill('Nous recherchons un Product Designer maîtrisant Figma et la recherche utilisateur.')
  await page.getByRole('button', { name: 'Analyser l’offre' }).click()
  await expect(page).toHaveURL(/\/analyses\//)
  await page.reload()
  await expect(page.getByText('82%', { exact: true })).toBeVisible()
  await expect(page.getByText('Correspondances solides')).toBeVisible()
  await expect(page.getByText('Le contexte de pratique reste à détailler.')).toBeVisible()
  await expect(page.getByText('Jira est apprécié mais absent du CV.')).toBeVisible()
  await page.getByRole('button', { name: 'Générer une lettre de motivation' }).click()
  await expect(page.getByLabel('Objet de la lettre')).toHaveValue('Candidature Product Designer')
  await page.getByLabel('Contenu de la lettre').fill('Madame, Monsieur, cette lettre a été relue avant son enregistrement.')
  await page.getByRole('button', { name: 'Enregistrer dans mes lettres' }).click()
  await expect(page).toHaveURL(/\/lettres\//)
})

test('analyse enregistrée : création contrôlée d’une copie adaptée du CV', async ({ page }) => {
  const state = await authenticatedPage(page)
  state.user.plan = 'pro'
  await page.goto('/analyses/' + state.jobAnalysis.id_job_analysis)
  await page.getByRole('button', { name: 'Adapter mon CV à cette offre' }).click()
  await expect(page.getByText('Product Designer spécialisé dans les parcours utilisateurs et Figma.')).toBeVisible()
  await page.getByRole('button', { name: 'Accepter', exact: true }).click()
  await page.getByRole('button', { name: /Créer mon CV adapté/ }).click()
  await expect(page).toHaveURL(/\/cv\/cc8dc2f2-6ff2-43d2-9e4f-5443200f6d4b$/)
})

test('candidature : entretien, simulation, remerciement et timeline persistent', async ({ page }) => {
  const state = await authenticatedPage(page)
  state.user.plan = 'pro'
  state.applications.push({ id_application: 'aa8dc2f2-6ff2-43d2-9e4f-5443200f6d4b', company_name: 'Novyata', job_title: 'Product Designer', status: 'Entretien', id_resume: state.resume.id_resume, id_job_analysis: state.jobAnalysis.id_job_analysis })
  await page.goto('/candidatures/aa8dc2f2-6ff2-43d2-9e4f-5443200f6d4b')
  await page.getByLabel('Type d’entretien').fill('Visio')
  await page.getByLabel('Points importants').fill('Présentation du portfolio')
  await page.getByRole('button', { name: 'Enregistrer le compte-rendu' }).click()
  await page.getByRole('button', { name: 'Préparer l’entretien' }).click()
  await expect(page.getByRole('heading', { name: 'Questions RH' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Questions métier' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Questions comportementales' })).toBeVisible()
  await page.getByRole('button', { name: 'Démarrer la simulation' }).click()
  await expect(page.getByText('Pourquoi ce poste vous intéresse-t-il ?', { exact: true })).toBeVisible()
  await page.getByLabel('Votre réponse').fill('Le produit et les missions correspondent à mon expérience réelle.')
  await page.getByRole('button', { name: 'Envoyer ma réponse' }).click()
  await expect(page.getByText('Comment collaborez-vous avec une équipe produit ?', { exact: true })).toBeVisible()
  await expect(page.getByText('Précisez la situation, votre tâche, les actions et le résultat réel.').first()).toBeVisible()
  await page.getByRole('button', { name: 'Terminer la simulation' }).click()
  await page.getByRole('button', { name: 'Générer un remerciement' }).click()
  await expect(page.getByText('Merci pour notre échange.')).toBeVisible()
  await page.getByRole('button', { name: 'Marquer envoyé' }).click()
  await expect(page.getByText('Relance envoyée')).toBeVisible()
  await page.reload()
  const savedSimulation = page.getByLabel('Reprendre une simulation')
  await expect(savedSimulation).toContainText('Terminée')
  await savedSimulation.selectOption('simulation-e2e')
  await expect(page.getByText('Le produit et les missions correspondent à mon expérience réelle.')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Comment collaborez-vous avec une équipe produit ?' })).toBeVisible()
  await expect(page.getByText('Relance envoyée')).toBeVisible()
})

test('offres : import URL, comparaison multi-CV puis comparaison d’analyses sauvegardées', async ({ page }) => {
  const state = await authenticatedPage(page)
  state.user.plan = 'pro'
  await page.goto('/analyse-offre')
  await page.getByLabel('URL publique de l’offre').fill('https://jobs.example/data-analyst')
  await page.getByRole('button', { name: 'Importer l’offre' }).click()
  await expect(page.getByLabel('Entreprise')).toHaveValue('Atlas')
  await expect(page.getByLabel('Poste visé')).toHaveValue('Data Analyst')
  await page.getByRole('button', { name: 'Comparer mes CV' }).click()
  await expect(page.getByText('Correspondance estimée')).toBeVisible()
  await expect(page.getByText('CV Data')).toBeVisible()
  await page.getByLabel('CV à analyser').selectOption({ index: 1 })
  await page.getByRole('button', { name: 'Analyser l’offre' }).click()
  await expect(page).toHaveURL(/\/analyses\//)

  await page.goto('/analyses')
  await page.getByLabel('Sélectionner Novyata').check()
  await page.getByLabel('Sélectionner Studio Atlas').check()
  await page.getByRole('button', { name: 'Comparer les offres (2)' }).click()
  await expect(page).toHaveURL(/\/analyses\/comparer/)
  await expect(page.getByRole('heading', { name: 'Comparer des offres' })).toBeVisible()
  await expect(page.getByText('CDI')).toBeVisible()
  await expect(page.getByText('Non précisé dans l’offre').first()).toBeVisible()
})
