import { expect, test } from '@playwright/test'
import { authenticatedPage, mockApi } from './fixtures.js'

test('authentification : inscription, dashboard, déconnexion et route privée', async ({ page }) => {
  await mockApi(page)
  await page.goto('/dashboard')
  await expect(page).toHaveURL(/\/connexion$/)
  await page.goto('/inscription')
  await page.getByLabel('Prénom').fill('Élise')
  await page.getByLabel('Nom', { exact: true }).fill('Durand')
  await page.getByLabel('Adresse e-mail').fill('elise.e2e@example.test')
  await page.locator('input[name="password"]').fill('password-e2e')
  await page.getByLabel('Confirmer le mot de passe').fill('password-e2e')
  await page.getByRole('button', { name: 'Créer mon compte' }).click()
  await expect(page).toHaveURL(/\/dashboard$/)
  await expect(page.getByRole('heading', { name: "Vue d'ensemble" })).toBeVisible()
  await page.getByRole('button', { name: 'Déconnexion' }).click()
  await expect(page).toHaveURL(/\/connexion$/)
})

test('CV : création, personnalisation et réouverture', async ({ page }) => {
  await authenticatedPage(page)
  await page.goto('/cv/nouveau')
  await page.getByLabel('Titre du CV').fill('CV produit E2E')
  await page.getByLabel('Poste recherché').fill('Product Designer')
  await page.getByRole('button', { name: 'Créer mon CV' }).click()
  await expect(page).toHaveURL(/\/cv\//)
  await page.getByRole('button', { name: 'Ajouter une expérience' }).click()
  await page.getByRole('combobox').last().fill('Designer produit')
  await page.getByLabel('Entreprise').last().fill('Novyata')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).last().click()
  await page.getByRole('button', { name: 'Ajouter une formation' }).click()
  await page.getByLabel('Diplôme / Formation').fill('Master design')
  await page.getByLabel('Établissement').fill('École E2E')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).last().click()
  await page.getByLabel('Ajouter une compétence personnalisée').fill('Figma')
  await page.getByRole('button', { name: '+ Ajouter', exact: true }).click()
  await page.getByRole('button', { name: 'Moderne' }).click()
  await page.getByRole('button', { name: 'Grand' }).click()
  await page.getByLabel('Prénom').fill('Élise')
  await page.getByRole('button', { name: 'Enregistrer', exact: true }).first().click()
  await page.reload()
  await expect(page.getByText('CV produit E2E')).toBeVisible()
  await page.locator('.editor-actions').getByRole('button', { name: 'Supprimer', exact: true }).click()
  await page.getByRole('button', { name: 'Supprimer définitivement' }).click()
  await expect(page).toHaveURL(/\/dashboard$/)
})

test('dépassement A4 : sauvegarde et export sont bloqués', async ({ page }) => {
  const state = await authenticatedPage(page)
  state.resume.summary = 'Contenu de test très long. '.repeat(800)
  await page.goto('/cv/f8c5d2f2-6ff2-43d2-9e4f-5443200f6d4b')
  await expect(page.getByRole('alert')).toContainText('dépasse une page A4')
  await expect(page.getByRole('button', { name: 'Télécharger en PDF' })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Enregistrer', exact: true }).first()).toBeDisabled()
})

test('lettres et candidatures : liaison, sauvegarde, statut et filtre', async ({ page }) => {
  await authenticatedPage(page)
  await page.goto('/lettres/nouvelle')
  await page.getByLabel('Titre interne').fill('Lettre Novyata')
  await page.getByLabel('CV associé').selectOption({ index: 1 })
  await page.getByLabel('Contenu').fill('Madame, Monsieur, je souhaite vous proposer ma candidature pour ce poste de Product Designer.')
  await page.getByRole('button', { name: 'Créer la lettre' }).click()
  await expect(page).toHaveURL(/\/lettres\//)
  await page.getByLabel('Objet').fill('Candidature Product Designer')
  await page.getByRole('button', { name: 'Enregistrer les modifications' }).click()
  await expect(page.getByText('Modifications enregistrées.')).toBeVisible()
  await page.goto('/candidatures/nouvelle')
  await page.getByLabel('Entreprise').fill('Novyata')
  await page.getByLabel('Poste').fill('Product Designer')
  await page.getByLabel('CV associé').selectOption({ index: 1 })
  await page.getByLabel('Lettre associée').selectOption({ index: 1 })
  await page.getByLabel('Statut').selectOption('Entretien')
  await page.getByRole('button', { name: 'Ajouter la candidature' }).click()
  await expect(page).toHaveURL(/\/candidatures\//)
  await page.goto('/candidatures')
  await expect(page.getByText('Novyata')).toBeVisible()
  await page.getByRole('combobox').nth(0).selectOption('Entretien')
  await expect(page.getByText('Product Designer')).toBeVisible()
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Supprimer Novyata' }).click()
  await expect(page.getByText('Vous n’avez encore aucune candidature.')).toBeVisible()
})

test('analyse d’offre : résultat, génération puis sauvegarde de lettre mockés', async ({ page }) => {
  await authenticatedPage(page)
  await page.goto('/analyse-offre')
  await page.getByLabel('CV à analyser').selectOption({ index: 1 })
  await page.getByLabel('Texte de l’offre').fill('Nous recherchons un Product Designer maîtrisant Figma et la recherche utilisateur.')
  await page.getByRole('button', { name: 'Analyser l’offre' }).click()
  await expect(page).toHaveURL(/\/analyses\//)
  await page.reload()
  await expect(page.getByText('82%', { exact: true })).toBeVisible()
  await expect(page.getByText('Correspondances solides')).toBeVisible()
  await expect(page.getByText('Le contexte de pratique reste à détailler.')).toBeVisible()
  await expect(page.getByText('Jira est apprécié mais absent du CV.')).toBeVisible()
  await page.getByRole('button', { name: 'Générer une lettre de motivation' }).click()
  await expect(page.getByLabel('Objet de la lettre')).toHaveValue('Candidature Product Designer')
  await page.getByLabel('Contenu de la lettre').fill('Madame, Monsieur, cette lettre a été relue avant son enregistrement.')
  await page.getByRole('button', { name: 'Enregistrer dans mes lettres' }).click()
  await expect(page).toHaveURL(/\/lettres\//)
})

test('analyse enregistrée : création contrôlée d’une copie adaptée du CV', async ({ page }) => {
  const state = await authenticatedPage(page)
  await page.goto('/analyses/' + state.jobAnalysis.id_job_analysis)
  await page.getByRole('button', { name: 'Adapter mon CV à cette offre' }).click()
  await expect(page.getByText('Product Designer spécialisé dans les parcours utilisateurs et Figma.')).toBeVisible()
  await page.getByRole('button', { name: 'Accepter', exact: true }).click()
  await page.getByRole('button', { name: /Créer mon CV adapté/ }).click()
  await expect(page).toHaveURL(/\/cv\/cc8dc2f2-6ff2-43d2-9e4f-5443200f6d4b$/)
})
