const ids = {
  user: '8b74e3e1-64b4-46f1-bfd8-c50a174cf908',
  resume: 'f8c5d2f2-6ff2-43d2-9e4f-5443200f6d4b',
  letter: 'fa8dc2f2-6ff2-43d2-9e4f-5443200f6d4b',
  application: 'aa8dc2f2-6ff2-43d2-9e4f-5443200f6d4b',
  adaptedResume: 'cc8dc2f2-6ff2-43d2-9e4f-5443200f6d4b',
}

export const user = { id_user: ids.user, first_name: 'Élise', last_name: 'Durand', email: 'elise.e2e@example.test', plan: 'free', job_search_preferences: {}, created_at: '2026-01-01T00:00:00.000Z' }

export async function mockApi(page) {
  const state = {
    user: { ...user },
    resumeEvents: [],
    resumeVersions: [],
    resume: { id_resume: ids.resume, title_resume: 'CV E2E', first_name: 'Élise', last_name: 'Durand', email: user.email, phone: '0600000000', city: 'Paris', job_title: 'Product Designer', summary: 'Profil de test.', template_key: 'classic', accent_color: '#314A67', font_size: 'normal', font_family: 'Inter', content_density: 'normal', section_spacing: 'normal', heading_style: 'line', divider_style: 'solid', section_order: ['summary', 'experiences', 'educations', 'skills', 'languages'], custom_sections: [], variants: [], experiences: [], educations: [], skills: [], languages: [], created_at: user.created_at, updated_at: user.created_at },
    letter: { id_cover_letter: ids.letter, id_resume: ids.resume, title: 'Lettre E2E', company_name: 'Novyata', job_title: 'Product Designer', recipient_name: '', recipient_position: '', company_address: '', subject: 'Candidature', content: 'Madame, Monsieur, je souhaite vous proposer ma candidature pour ce poste.', template: 'classic', created_at: user.created_at, updated_at: user.created_at },
    applications: [],
    notifications: [],
    events: [],
    interviews: [],
    followups: [],
    interviewSessions: [],
    adaptedResume: null,
    importSaved: false,
    publicProfile: null,
    resumeShareLinks: [],
    weeklyGoal: { is_enabled: false, target_applications: 5, target_followups: 2, target_interviews: 1 },
    jobAnalysis: { id_job_analysis: 'bb8dc2f2-6ff2-43d2-9e4f-5443200f6d4b', id_resume: ids.resume, title_resume: 'CV E2E', company_name: 'Novyata', job_title: 'Product Designer', job_description: 'Nous recherchons un Product Designer maîtrisant Figma.', match_score: 82, analysis: { id_job_analysis: 'bb8dc2f2-6ff2-43d2-9e4f-5443200f6d4b', matchScore: 82, requirements: [{ name: 'Figma', category: 'essential' }, { name: 'Recherche utilisateur', category: 'secondary' }, { name: 'Jira', category: 'bonus' }], strongMatches: [{ name: 'Figma', evidence: 'Figma', reason: 'Compétence citée dans le CV.' }], partialMatches: [{ name: 'Recherche utilisateur', evidence: 'Profil de test.', reason: 'Le contexte de pratique reste à détailler.' }], importantMissingSkills: [], optionalMissingSkills: [{ name: 'Jira', reason: 'Jira est apprécié mais absent du CV.' }], importantKeywords: ['Produit'], suggestions: ['Décrivez un projet où vous avez utilisé Figma.'], scoreExplanation: 'Les exigences essentielles ont le poids le plus élevé.', safetyNote: 'N’ajoutez une compétence à votre CV que si vous la maîtrisez réellement.' }, created_at: user.created_at, updated_at: user.created_at },
    jobAnalysisOther: { id_job_analysis: 'dd8dc2f2-6ff2-43d2-9e4f-5443200f6d4b', id_resume: ids.resume, title_resume: 'CV E2E', company_name: 'Studio Atlas', job_title: 'Product Designer', job_description: 'Localisation : Lyon\nContrat : CDI\nTélétravail hybride, 2 jours par semaine.\nRémunération : 40 000 €\nAvantages : mutuelle.', match_score: 69, analysis: { requirements: [{ name: 'Figma' }, { name: 'Design system' }] }, created_at: user.created_at, updated_at: user.created_at },
  }
  const json = (route, value, status = 200) => route.fulfill({ status, contentType: 'application/json', body: JSON.stringify(value) })
  const body = (request) => { try { return JSON.parse(request.postData() || '{}') } catch { return {} } }

  await page.route('**/api/v1/**', async (route) => {
    const request = route.request(); const method = request.method(); const path = new URL(request.url()).pathname; const payload = body(request)
    if (path === '/api/v1/auth/register' || path === '/api/v1/auth/login') return json(route, { user: state.user, token: 'e2e-token' }, path.endsWith('register') ? 201 : 200)
    if (path === '/api/v1/auth/me/search-preferences' && method === 'PATCH') { state.user.job_search_preferences = Object.fromEntries(Object.entries(payload).filter(([, value]) => value)); return json(route, { user: state.user }) }
    if (path === '/api/v1/auth/me') return json(route, { user: state.user })
    if (path === '/api/v1/weekly-goals' && method === 'GET') return json(route, { goal: state.weeklyGoal, week_start: '2026-09-28', progress: { applications: state.applications.length, followups: 0, interviews: state.interviewSessions.length } })
    if (path === '/api/v1/weekly-goals' && method === 'PUT') { state.weeklyGoal = payload; return json(route, { goal: state.weeklyGoal, week_start: '2026-09-28', progress: { applications: state.applications.length, followups: 0, interviews: state.interviewSessions.length } }) }
    if (path === '/api/v1/portfolio/me' && method === 'GET') return json(route, { profile: state.publicProfile, defaults: { name: false, job_title: false, summary: false, experiences: false, educations: false, skills: false, languages: false, custom_sections: false } })
    if (path === '/api/v1/portfolio/me' && method === 'PUT') { state.publicProfile = { ...payload, id_resume: payload.id_resume || null }; return json(route, { profile: state.publicProfile }) }
    if (path.startsWith('/api/v1/portfolio/') && path !== '/api/v1/portfolio/me' && method === 'GET') { if (!state.publicProfile?.is_published || decodeURIComponent(path.split('/').at(-1)) !== state.publicProfile.slug) return json(route, { error: { message: 'Portfolio introuvable.' } }, 404); const visible = state.publicProfile.visible_sections; return json(route, { portfolio: { name: visible.name ? 'Élise Durand' : null, jobTitle: visible.job_title ? state.resume.job_title : null, summary: visible.summary ? state.resume.summary : null, experiences: visible.experiences ? state.resume.experiences : [], educations: [], skills: [], languages: [], customSections: [] } }) }
    const shareCollectionMatch = path.match(/^\/api\/v1\/resumes\/([^/]+)\/share-links$/)
    if (shareCollectionMatch && method === 'GET') return json(route, { links: state.resumeShareLinks })
    if (shareCollectionMatch && method === 'POST') { const link = { id_resume_share_link: 'share-e2e', include_contact_details: payload.includeContactDetails, expires_at: payload.expiresInDays ? new Date(Date.now() + payload.expiresInDays * 86400000).toISOString() : null, revoked_at: null, created_at: new Date().toISOString(), path: '/cv/share/' + 'A'.repeat(43) }; state.resumeShareLinks.unshift(link); return json(route, { link }, 201) }
    const shareLinkMatch = path.match(/^\/api\/v1\/resumes\/([^/]+)\/share-links\/([^/]+)$/)
    if (shareLinkMatch && method === 'DELETE') { const link = state.resumeShareLinks.find((item) => item.id_resume_share_link === shareLinkMatch[2]); if (link) link.revoked_at = new Date().toISOString(); return json(route, { link }) }
    const sharedResumeMatch = path.match(/^\/api\/v1\/shared-resumes\/(.+)$/)
    if (sharedResumeMatch && method === 'GET') { const link = state.resumeShareLinks.find((item) => item.path?.endsWith(decodeURIComponent(sharedResumeMatch[1])) && !item.revoked_at); if (!link) return json(route, { error: { message: 'CV partagé introuvable ou indisponible.' } }, 404); const resume = { ...state.resume }; if (!link.include_contact_details) { delete resume.email; delete resume.phone; delete resume.city }; return json(route, { resume }) }
    if (path === '/api/v1/notifications' && method === 'GET') return json(route, { notifications: state.notifications.filter((item) => !item.archived_at), unreadCount: state.notifications.filter((item) => !item.is_read && !item.archived_at).length })
    if (path === '/api/v1/notifications' && method === 'POST') { const item = { id_notification: 'next-action-e2e', type: 'next_action', is_read: false, scheduled_for: payload.scheduled_for, ...payload }; state.notifications.push(item); return json(route, { notification: item }, 201) }
    if (path === '/api/v1/notifications/read-all' && method === 'PATCH') { state.notifications.forEach((item) => { if (!item.archived_at) item.is_read = true }); return json(route, { updatedCount: state.notifications.length }) }
    if (path === '/api/v1/notifications/archive-all' && method === 'PATCH') { state.notifications.forEach((item) => { item.archived_at = new Date().toISOString(); item.is_read = true }); return json(route, { archivedCount: state.notifications.length }) }
    const notificationReadMatch = path.match(/^\/api\/v1\/notifications\/([^/]+)\/read$/)
    if (notificationReadMatch && method === 'PATCH') { const item = state.notifications.find((entry) => entry.id_notification === notificationReadMatch[1]); if (item) item.is_read = payload.is_read; return json(route, { notification: item }) }
    const notificationArchiveMatch = path.match(/^\/api\/v1\/notifications\/([^/]+)\/archive$/)
    if (notificationArchiveMatch && method === 'PATCH') { const item = state.notifications.find((entry) => entry.id_notification === notificationArchiveMatch[1]); if (item) { item.archived_at = new Date().toISOString(); item.is_read = true }; return json(route, { notification: item }) }
    const notificationDeleteMatch = path.match(/^\/api\/v1\/notifications\/([^/]+)$/)
    if (notificationDeleteMatch && method === 'DELETE') { state.notifications = state.notifications.filter((entry) => entry.id_notification !== notificationDeleteMatch[1]); return route.fulfill({ status: 204 }) }
    if (path === '/api/v1/activity' && method === 'GET') return json(route, { activity: [{ kind: 'Analyse d’offre', id: state.jobAnalysis.id_job_analysis, title: state.jobAnalysis.company_name, subtitle: state.jobAnalysis.job_title, date: user.created_at, href: `/analyses/${state.jobAnalysis.id_job_analysis}` }] })
    if (path === '/api/v1/resumes' && method === 'GET') return json(route, { resumes: [state.resume, ...(state.variant ? [state.variant] : [])] })
    if (path === '/api/v1/resumes/compare' && method === 'POST') return json(route, { left: { id_resume: ids.resume, title_resume: state.resume.title_resume, job_title: state.resume.job_title }, right: { id_resume: state.variant?.id_resume, title_resume: state.variant?.title_resume, job_title: state.variant?.job_title }, diff: { summary: { before: state.resume.summary, after: state.variant?.summary || 'Profil adapté.' }, experiences: { added: [], removed: [], modified: [] }, educations: { added: [], removed: [], modified: [] }, skills: { added: [], removed: [], modified: [] }, languages: { added: [], removed: [], modified: [] }, customSections: { added: [], removed: [], modified: [] }, sectionOrder: null, appearance: {} } })
    const resumeVersionMatch = path.match(/^\/api\/v1\/resumes\/([^/]+)\/versions$/)
    if (resumeVersionMatch && method === 'GET') return json(route, { versions: state.resumeVersions })
    const resumeVersionActionMatch = path.match(/^\/api\/v1\/resumes\/([^/]+)\/versions\/([^/]+)\/(restore|duplicate)$/)
    if (resumeVersionActionMatch && method === 'POST') { const copyId = resumeVersionActionMatch[3] === 'restore' ? 'restored-e2e' : 'version-copy-e2e'; state.versionCopy = { ...state.resume, id_resume: copyId, title_resume: `${state.resume.title_resume} — Copie` }; return json(route, { resume: state.versionCopy }, 201) }
    if (path === '/api/v1/resumes' && method === 'POST') { state.resume = { ...state.resume, ...payload, id_resume: ids.resume, experiences: [], educations: [], skills: [], languages: [] }; return json(route, { resume: state.resume }, 201) }
    if (path === `/api/v1/resume-tools/${ids.resume}/summary` && method === 'POST') return json(route, { suggestion: 'Product Designer spécialisé en conception de parcours et prototypage d’interfaces.' })
    if (path === `/api/v1/resume-tools/${ids.resume}/summary/improve` && method === 'POST') return json(route, { suggestion: 'Product Designer expérimentée, conçoit des parcours et réalise des tests utilisateurs.' })
    if (path === `/api/v1/resume-tools/${ids.resume}/experiences/experience-e2e/improve` && method === 'POST') return json(route, { suggestion: 'Conception de parcours utilisateurs et tests de prototypes avec l’équipe produit.' })
    if (path === '/api/v1/resumes/import/parse' && method === 'POST') return json(route, { import: { format: 'pdf', title_resume: 'CV Élise Durand', first_name: 'Élise', last_name: 'Durand', job_title: 'Product Designer', email: user.email, phone: '', city: 'Paris', summary: 'Profil de test extrait.', experiences: [], educations: [], skills: [{ name: 'Figma', level: '' }], languages: [], needs_review: ['experiences'], raw_text: 'Élise Durand\nProduct Designer' } })
    if (path === '/api/v1/resumes/import' && method === 'POST') { state.importSaved = true; state.resume = { ...state.resume, ...payload, id_resume: 'import-e2e', experiences: payload.experiences || [], educations: payload.educations || [], skills: payload.skills || [], languages: payload.languages || [] }; return json(route, { resume: state.resume }, 201) }
    if (path === `/api/v1/resumes/${ids.resume}` && method === 'GET') return json(route, { resume: state.resume })
    if (path === '/api/v1/resumes/import-e2e' && method === 'GET') return json(route, { resume: state.resume })
    if (path === `/api/v1/resumes/${ids.adaptedResume}` && method === 'GET') return json(route, { resume: state.adaptedResume || state.resume })
    if (path === '/api/v1/resumes/variant-e2e' && method === 'GET') return json(route, { resume: state.variant || state.resume })
    if (/^\/api\/v1\/resumes\/[^/]+$/.test(path) && method === 'GET') { const id = path.split('/').at(-1); return json(route, { resume: [state.resume, state.variant, state.adaptedResume, state.versionCopy].find((item) => item?.id_resume === id) || state.resume }) }
    if (path === `/api/v1/resumes/${ids.resume}` && method === 'PATCH') { state.resumeEvents.push({ method, section_order: payload.section_order, template_key: payload.template_key }); state.resume = { ...state.resume, ...payload }; return json(route, { resume: state.resume }) }
    if (path === `/api/v1/resumes/${ids.resume}/section-order` && method === 'PUT') { state.resumeEvents.push({ method, section_order: payload.section_order }); state.resume.section_order = payload.section_order; return json(route, { section_order: state.resume.section_order }) }
    if (path === `/api/v1/resumes/${ids.resume}/sections` && method === 'POST') { const section = { id_resume_section: 'custom-e2e', id_resume: ids.resume, ...payload }; state.resume.custom_sections.push(section); return json(route, { section }, 201) }
    if (path === `/api/v1/resumes/${ids.resume}/sections/custom-e2e` && method === 'PATCH') { state.resume.custom_sections = state.resume.custom_sections.map((item) => item.id_resume_section === 'custom-e2e' ? { ...item, ...payload } : item); return json(route, { section: state.resume.custom_sections[0] }) }
    if (path === `/api/v1/resumes/${ids.resume}/sections/custom-e2e` && method === 'DELETE') { state.resume.custom_sections = []; return route.fulfill({ status: 204 }) }
    if (path === `/api/v1/resumes/${ids.resume}/variants` && method === 'POST') { state.variant = { ...state.resume, id_resume: 'variant-e2e', parent_resume_id: ids.resume, title_resume: payload.title_resume, variants: [], custom_sections: [...state.resume.custom_sections] }; state.resume.variants.push({ id_resume: state.variant.id_resume, title_resume: state.variant.title_resume, job_title: state.variant.job_title, updated_at: user.created_at }); return json(route, { resume: state.variant }, 201) }
    if (path === `/api/v1/resumes/${ids.resume}` && method === 'DELETE') return route.fulfill({ status: 204 })
    if (path.includes(`/api/v1/resumes/${ids.resume}/experiences`) && method === 'POST') { const experience = { id_experience: 'e1', ...payload }; state.resume.experiences.push(experience); return json(route, { experience }, 201) }
    if (path === `/api/v1/resumes/${ids.resume}/experiences/experience-e2e` && method === 'PATCH') { state.resume.experiences[0] = { ...state.resume.experiences[0], ...payload }; return json(route, { experience: state.resume.experiences[0] }) }
    if (path.includes(`/api/v1/resumes/${ids.resume}/educations`) && method === 'POST') { const education = { id_education: 'd1', ...payload }; state.resume.educations.push(education); return json(route, { education }, 201) }
    if (path.includes(`/api/v1/resumes/${ids.resume}/skills`) && method === 'POST') { const skill = { id_skill: 's1', ...payload }; state.resume.skills.push(skill); return json(route, { skill }, 201) }
    if (path.includes(`/api/v1/resumes/${ids.resume}/languages`) && method === 'POST') { const language = { id_language: 'l1', ...payload }; state.resume.languages.push(language); return json(route, { language }, 201) }
    if (path === '/api/v1/cover-letters' && method === 'GET') return json(route, { cover_letters: [state.letter] })
    if (path === '/api/v1/cover-letters' && method === 'POST') { state.letter = { ...state.letter, ...payload, id_cover_letter: ids.letter }; return json(route, { cover_letter: state.letter }, 201) }
    if (path === `/api/v1/cover-letters/${ids.letter}` && method === 'GET') return json(route, { cover_letter: state.letter })
    if (path === `/api/v1/cover-letters/${ids.letter}` && method === 'PATCH') { state.letter = { ...state.letter, ...payload }; return json(route, { cover_letter: state.letter }) }
    if (path === `/api/v1/cover-letters/${ids.letter}` && method === 'DELETE') return route.fulfill({ status: 204 })
    if (path === '/api/v1/applications' && method === 'GET') return json(route, { applications: state.applications })
    if (path === '/api/v1/applications/advanced-statistics' && method === 'GET') return json(route, { periodDays: Number(new URL(request.url()).searchParams.get('period') || 90), funnel: { applications: 4, responses: 2, interviews: 1, offers: 0, refusals: 1 }, responseRate: 50, interviewRate: 25, averageResponseDelayDays: 6, responseDelaySampleSize: 2, weeklyTrend: [{ week: '2026-09-21', label: '21 sept.', applications: 1, responses: 0 }], outcomesByResume: [{ resumeId: ids.resume, resumeTitle: 'CV E2E', applications: 4, responses: 2, interviews: 1, offers: 0 }], historyNote: 'Données descriptives de test.' })
    if (path === '/api/v1/applications' && method === 'POST') { const application = { id_application: ids.application, ...payload, updated_at: user.created_at }; state.applications.push(application); return json(route, { application }, 201) }
    if (path === `/api/v1/applications/${ids.application}` && method === 'GET') return json(route, { application: state.applications[0] })
    if (path === `/api/v1/applications/${ids.application}/dossier` && method === 'GET') return json(route, { application: state.applications[0], events: state.events, interviews: state.interviews, followups: state.followups, interview_sessions: state.interviewSessions, checklist: [] })
    if (path === `/api/v1/applications/${ids.application}/interviews` && method === 'POST') { const item = { id_interview: 'interview-e2e', ...payload }; state.interviews.push(item); state.events.unshift({ id_application_event: 'event-interview', event_date: '2026-01-02', title: 'Compte-rendu d’entretien ajouté' }); return json(route, { interview: item }, 201) }
    if (path === `/api/v1/applications/${ids.application}/interview-preparation` && method === 'POST') return json(route, { preparation: { introduction: 'Je suis designer produit et j’ai travaillé sur des parcours utilisateur.', questions: [{ category: 'rh', question: 'Pourquoi souhaitez-vous rejoindre cette équipe ?' }, { category: 'technique', question: 'Comment abordez-vous la recherche utilisateur ?' }, { category: 'comportementale', question: 'Racontez une collaboration réelle.' }], strengths: ['Recherche utilisateur'], prepare: ['Préparer un exemple réel.'], recruiterQuestions: ['Comment est organisée l’équipe ?'] } })
    if (path === `/api/v1/applications/${ids.application}/interview-simulation` && method === 'POST') { const item = state.interviewSessions.find((entry) => entry.id_interview_session === payload.sessionId) || { id_interview_session: 'simulation-e2e', status: 'in_progress', exchanges: [], created_at: user.created_at, updated_at: user.created_at }; const feedback = { positives: ['Réponse structurée'], missing: 'Un exemple concret.', suggestion: 'Ajoutez une réalisation réelle.', ...(state.user.plan === 'pro' ? { starAdvice: 'Précisez la situation, votre tâche, les actions et le résultat réel.' } : {}) }; const question = item.exchanges.length ? 'Comment collaborez-vous avec une équipe produit ?' : 'Pourquoi ce poste vous intéresse-t-il ?'; if (payload.answer && item.exchanges.length) { item.exchanges.at(-1).answer = payload.answer; item.exchanges.at(-1).feedback = feedback }; const simulation = { question, feedback: payload.answer ? feedback : null }; item.exchanges.push({ question, answer: '', feedback: null }); item.progress = item.exchanges.filter((entry) => entry.answer).length; item.updated_at = new Date().toISOString(); if (!state.interviewSessions.includes(item)) state.interviewSessions.push(item); return json(route, { simulation, session: item }) }
    if (path === `/api/v1/applications/${ids.application}/interview-simulations/simulation-e2e/complete` && method === 'PATCH') { state.interviewSessions[0].status = 'completed'; return json(route, { session: state.interviewSessions[0] }) }
    if (path === `/api/v1/applications/${ids.application}/thank-you` && method === 'POST') { const item = { id_followup: 'thank-you-e2e', type: 'Remerciement', content: 'Merci pour notre échange.', sent_at: null }; state.followups.push(item); return json(route, { followup: item }, 201) }
    if (path === `/api/v1/applications/${ids.application}/followups/thank-you-e2e/sent` && method === 'PATCH') { state.followups[0].sent_at = '2026-01-02'; state.events.unshift({ id_application_event: 'event-thanks', event_date: '2026-01-02', title: 'Relance envoyée' }); return json(route, { followup: state.followups[0] }) }
    if (path === `/api/v1/applications/${ids.application}` && method === 'PATCH') { state.applications[0] = { ...state.applications[0], ...payload }; return json(route, { application: state.applications[0] }) }
    if (path === `/api/v1/applications/${ids.application}` && method === 'DELETE') return route.fulfill({ status: 204 })
    if (path === '/api/v1/job-analysis') return json(route, { analysis: state.jobAnalysis.analysis }, 201)
    if (path === '/api/v1/job-offer-import' && method === 'POST') return json(route, { offer: { sourceUrl: payload.url, companyName: 'Atlas', jobTitle: 'Data Analyst', description: 'Offre Atlas pour un Data Analyst avec SQL et Power BI, en CDI à Lyon.', location: 'Lyon', contractType: 'CDI', remote: '', salary: '', warnings: [] } })
    if (path === '/api/v1/resume-matching' && method === 'POST') return json(route, { matching: { confidence: 'estimated', note: 'Estimation descriptive.', skillsCompared: 2, results: [{ resumeId: ids.resume, title: 'CV E2E', jobTitle: 'Product Designer', score: 50, matchedSkills: ['SQL'], missingSkills: ['Power BI'] }, { resumeId: 'variant-e2e', title: 'CV Data', jobTitle: 'Data Analyst', score: 100, matchedSkills: ['SQL', 'Power BI'], missingSkills: [] }] } })
    if (path === '/api/v1/job-analyses' && method === 'GET') return json(route, { job_analyses: [state.jobAnalysis, state.jobAnalysisOther] })
    if (path === '/api/v1/job-analyses/compare' && method === 'POST') return json(route, { offers: payload.analysisIds.map((id) => { const item = [state.jobAnalysis, state.jobAnalysisOther].find((analysis) => analysis.id_job_analysis === id); return { id, companyName: item.company_name, jobTitle: item.job_title, location: item.company_name === 'Studio Atlas' ? 'Lyon' : '', contractType: item.company_name === 'Studio Atlas' ? 'CDI' : '', remote: '', salary: '', matchScore: item.match_score, importantRequirements: item.analysis.requirements.map((requirement) => requirement.name), explicitBenefits: [] } }) })
    if (path === `/api/v1/job-analyses/${state.jobAnalysis.id_job_analysis}` && method === 'GET') return json(route, { job_analysis: state.jobAnalysis })
    if (path === `/api/v1/job-analyses/${state.jobAnalysis.id_job_analysis}/cv-adaptation` && method === 'POST') return json(route, { adaptation: { proposals: [{ id: 'summary-1', field: 'summary', targetIndex: 0, currentText: 'Profil de test.', proposedText: 'Product Designer spécialisé dans les parcours utilisateurs et Figma.', reason: 'Met en avant des éléments déjà présents.' }] } })
    if (path === `/api/v1/job-analyses/${state.jobAnalysis.id_job_analysis}/cv-adaptation/apply` && method === 'POST') { state.adaptedResume = { ...state.resume, id_resume: ids.adaptedResume, title_resume: 'CV E2E — Novyata', summary: payload.acceptedIds?.includes('summary-1') ? 'Product Designer spécialisé dans les parcours utilisateurs et Figma.' : state.resume.summary }; return json(route, { resume: { id_resume: ids.adaptedResume, title_resume: state.adaptedResume.title_resume }, appliedCount: payload.acceptedIds?.length || 0 }, 201) }
    if (path === `/api/v1/job-analyses/${state.jobAnalysis.id_job_analysis}` && method === 'DELETE') return route.fulfill({ status: 204 })
    if (path === '/api/v1/cover-letter-generation') return json(route, { generation: { subject: 'Candidature Product Designer', content: 'Madame, Monsieur, je souhaite vous proposer ma candidature pour le poste de Product Designer.' } })
    return json(route, { error: { message: `Route E2E non mockée : ${method} ${path}` } }, 500)
  })
  return state
}

export async function authenticatedPage(page) {
  await page.addInitScript(() => localStorage.setItem('novyata_auth_token', 'e2e-token'))
  return mockApi(page)
}
