import { CirclePlus, Trash2 } from 'lucide-react'
import { useMemo, useState } from 'react'
import Button from '../common/Button'
import { createLanguage, createSkill, deleteLanguage, deleteSkill, updateLanguage, updateSkill } from '../../services/resumeService'
import { skillCategories } from '../../data/skillSuggestions'
import { jobSkillSuggestions } from '../../data/jobSkillSuggestions'

const levels = { skill: ['Débutant', 'Intermédiaire', 'Avancé', 'Expert'], language: ['Débutant', 'Intermédiaire', 'Courant', 'Bilingue', 'Langue maternelle'] }
const normalize = (value) => value.trim().toLocaleLowerCase('fr')
function TagCard({ item, kind, onChange, onSave, onDelete, saving, isOverflow }) { return <article className="resume-section-card tag-card"><div className={kind === 'skill' ? '' : 'editor-field-grid'}><label>{kind === 'skill' ? 'Compétence' : 'Langue'}<input value={item.name} onChange={(event) => onChange('name', event.target.value)} /></label>{kind === 'language' && <label>Niveau<select value={item.level} onChange={(event) => onChange('level', event.target.value)}><option value="">Sélectionner</option>{levels[kind].map((level) => <option key={level}>{level}</option>)}</select></label>}</div><div className="tag-card-actions"><Button type="button" onClick={onSave} disabled={saving || isOverflow} title={isOverflow ? 'Réduisez le contenu ou la taille du texte pour enregistrer.' : undefined}>{saving ? 'Enregistrement…' : 'Enregistrer'}</Button><button type="button" className="section-delete" onClick={onDelete}><Trash2 size={15} /> Supprimer</button></div></article> }

function SkillSelector({ items, addSkill, jobTitles }) {
  const [query, setQuery] = useState(''); const [category, setCategory] = useState('Toutes')
  const selected = new Set(items.map((item) => normalize(item.name || '')))
  const skills = useMemo(() => Object.entries(skillCategories).flatMap(([group, names]) => names.map((name) => ({ group, name }))).filter(({ group, name }) => (category === 'Toutes' || category === group) && name.toLocaleLowerCase('fr').includes(query.toLocaleLowerCase('fr'))), [category, query])
  const recommended = [...new Set(jobTitles.flatMap((title) => jobSkillSuggestions[normalize(title)] || []))]
  const chip = (name) => <button type="button" key={name} className={selected.has(normalize(name)) ? 'selected' : ''} onClick={() => addSkill(name)}>{selected.has(normalize(name)) ? '✓ ' : '+ '}{name}</button>
  return <div className="skill-selector"><label>Rechercher une compétence<input value={query} placeholder="Rechercher une compétence..." onChange={(event) => setQuery(event.target.value)} /></label><div className="skill-category-filter">{['Toutes', ...Object.keys(skillCategories)].map((name) => <button type="button" key={name} className={category === name ? 'active' : ''} onClick={() => setCategory(name)}>{name}</button>)}</div>{recommended.length > 0 && <div className="recommended-skills"><b>Compétences recommandées pour votre métier</b><div className="skill-chips">{recommended.map(chip)}</div></div>}<div className="skill-chips">{skills.map(({ name }) => chip(name))}</div><div className="custom-skill"><input value={query} placeholder="Ex. Prisma" onChange={(event) => setQuery(event.target.value)} /><Button type="button" variant="secondary" onClick={() => { addSkill(query); setQuery('') }} disabled={!query.trim()}>+ Ajouter</Button></div></div>
}

function TagSection({ title, kind, resumeId, items, setItems, jobTitles = [], isOverflow = false }) {
  const [saving, setSaving] = useState(''); const [error, setError] = useState(''); const idKey = kind === 'skill' ? 'id_skill' : 'id_language'; const create = kind === 'skill' ? createSkill : createLanguage; const update = kind === 'skill' ? updateSkill : updateLanguage; const remove = kind === 'skill' ? deleteSkill : deleteLanguage
  const add = (name) => { const value = name || ''; if (kind === 'skill' && name !== undefined && (!value.trim() || items.some((item) => normalize(item.name || '') === normalize(value)))) return; setItems((current) => [...current, { [idKey]: 'new-' + Date.now(), name: value, level: '' }]) }
  const change = (id, field, value) => setItems((current) => current.map((item) => item[idKey] === id ? { ...item, [field]: value } : item))
  const save = async (item) => { setSaving(item[idKey]); setError(''); try { const result = item[idKey].startsWith('new-') ? await create(resumeId, item) : await update(resumeId, item[idKey], item); setItems((current) => current.map((entry) => entry[idKey] === item[idKey] ? result[kind] : entry)) } catch (requestError) { setError(requestError.message) } finally { setSaving('') } }
  const del = async (item) => { setError(''); try { if (!item[idKey].startsWith('new-')) await remove(resumeId, item[idKey]); setItems((current) => current.filter((entry) => entry[idKey] !== item[idKey])) } catch (requestError) { setError(requestError.message) } }
  const toggleSkill = (name) => { const item = items.find((entry) => normalize(entry.name || '') === normalize(name)); if (!item) return add(name); setItems((current) => current.filter((entry) => entry[idKey] !== item[idKey])); if (!item[idKey].startsWith('new-')) remove(resumeId, item[idKey]).catch((requestError) => { setError(requestError.message); setItems((current) => [...current, item]) }) }
  return <section><div className="resume-section-heading"><div><p>Profil</p><h2>{title}</h2></div><button type="button" className="section-add" onClick={() => add()}><CirclePlus size={16} /> Ajouter une {kind === 'skill' ? 'compétence' : 'langue'}</button></div>{kind === 'skill' && <SkillSelector items={items} addSkill={toggleSkill} jobTitles={jobTitles} />}{error && <p className="editor-feedback editor-feedback--error" role="alert">{error}</p>}{items.map((item) => <TagCard key={item[idKey]} item={item} kind={kind} saving={saving === item[idKey]} isOverflow={isOverflow} onChange={(field, value) => change(item[idKey], field, value)} onSave={() => save(item)} onDelete={() => del(item)} />)}</section>
}
export default function ResumeTags(props) { return <div className="resume-sections"><TagSection title="Compétences" kind="skill" resumeId={props.resumeId} items={props.skills} setItems={props.setSkills} jobTitles={(props.experiences || []).map((item) => item.job_title).filter(Boolean)} isOverflow={props.isOverflow} /><TagSection title="Langues" kind="language" resumeId={props.resumeId} items={props.languages} setItems={props.setLanguages} isOverflow={props.isOverflow} /></div> }
