import { CirclePlus, Trash2, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import Button from '../common/Button'
import { createLanguage, createSkill, deleteLanguage, deleteSkill, updateLanguage, updateSkill } from '../../services/resumeService'
import { skillCategories } from '../../data/skillSuggestions'
import { jobSkillSuggestions } from '../../data/jobSkillSuggestions'

const levels = { skill: ['Débutant', 'Intermédiaire', 'Avancé', 'Expert'], language: ['Débutant', 'Intermédiaire', 'Courant', 'Bilingue', 'Langue maternelle'] }
const normalize = (value) => value.trim().toLocaleLowerCase('fr')
function TagCard({ item, kind, onChange, onSave, onDelete, saving, isOverflow }) { return <article className="resume-section-card tag-card"><div className={kind === 'skill' ? '' : 'editor-field-grid'}><label>{kind === 'skill' ? 'Compétence' : 'Langue'}<input value={item.name} onChange={(event) => onChange('name', event.target.value)} /></label>{kind === 'language' && <label>Niveau<select value={item.level} onChange={(event) => onChange('level', event.target.value)}><option value="">Sélectionner</option>{levels[kind].map((level) => <option key={level}>{level}</option>)}</select></label>}</div><div className="tag-card-actions"><Button type="button" onClick={onSave} disabled={saving || isOverflow} title={isOverflow ? 'Réduisez le contenu ou la taille du texte pour enregistrer.' : undefined}>{saving ? 'Enregistrement…' : 'Enregistrer'}</Button><button type="button" className="section-delete" onClick={onDelete}><Trash2 size={15} /> Supprimer</button></div></article> }

function SkillSelector({ items, addSkill, removeSkill, jobTitles }) {
  const [query, setQuery] = useState(''); const [category, setCategory] = useState('Toutes'); const [showAll, setShowAll] = useState(false); const [customSkill, setCustomSkill] = useState('')
  const selected = new Set(items.map((item) => normalize(item.name || '')))
  const allSkills = useMemo(() => Object.entries(skillCategories).flatMap(([group, names]) => names.map((name) => ({ group, name }))).filter(({ name }, index, list) => list.findIndex((item) => normalize(item.name) === normalize(name)) === index), [])
  const recommended = useMemo(() => [...new Set(jobTitles.flatMap((title) => jobSkillSuggestions[normalize(title)] || []))], [jobTitles])
  const filtered = allSkills.filter(({ group, name }) => (category === 'Toutes' || category === group) && name.toLocaleLowerCase('fr').includes(query.toLocaleLowerCase('fr')) && !selected.has(normalize(name)))
  const browsingLibrary = showAll || category !== 'Toutes' || Boolean(query.trim())
  const visibleSkills = browsingLibrary ? filtered.slice(0, 24) : [...new Set([...recommended, ...allSkills.slice(0, 6).map((item) => item.name)])].filter((name) => !selected.has(normalize(name))).slice(0, 8).map((name) => ({ group: 'suggestion', name }))

  return <div className="skill-selector"><div className="selected-skills"><b>Mes compétences</b>{items.length ? <div className="selected-skill-tags">{items.map((item) => <button type="button" key={item.id_skill} onClick={() => removeSkill(item)} aria-label={'Retirer ' + item.name}>{item.name}<X size={13} aria-hidden="true" /></button>)}</div> : <p>Ajoutez des compétences pour les retrouver ici.</p>}</div><label>Rechercher une compétence<input value={query} placeholder="Ex. React, Figma, PostgreSQL…" onChange={(event) => { setQuery(event.target.value); setCategory('Toutes') }} /></label><div className="skill-category-filter" aria-label="Catégories de compétences">{['Toutes', ...Object.keys(skillCategories)].map((name) => <button type="button" key={name} className={category === name ? 'active' : ''} onClick={() => { setCategory(name); if (name !== 'Toutes') setShowAll(true) }}>{name}</button>)}</div><div className="skill-library"><div className="skill-library-heading"><b>{browsingLibrary ? (category === 'Toutes' ? 'Résultats' : category) : 'Suggestions'}</b>{category === 'Toutes' && !query && <button type="button" className="skill-library-toggle" onClick={() => setShowAll((current) => !current)}>{showAll ? 'Réduire la liste' : 'Voir toutes les compétences'}</button>}</div>{visibleSkills.length ? <div className="skill-chips">{visibleSkills.map(({ group, name }) => <button type="button" key={group + '-' + name} onClick={() => addSkill(name)}>+ {name}</button>)}</div> : <p className="skill-empty">Aucune compétence correspondante.</p>}{browsingLibrary && filtered.length > visibleSkills.length && <small>Affichage des 24 premiers résultats. Affinez votre recherche pour préciser la liste.</small>}</div><div className="custom-skill"><input aria-label="Ajouter une compétence personnalisée" value={customSkill} placeholder="Ajouter une compétence personnalisée" onChange={(event) => setCustomSkill(event.target.value)} /><Button type="button" variant="secondary" onClick={async () => { await addSkill(customSkill); setCustomSkill('') }} disabled={!customSkill.trim()}>+ Ajouter</Button></div></div>
}

function TagSection({ title, kind, resumeId, items, setItems, jobTitles = [], isOverflow = false }) {
  const [saving, setSaving] = useState(''); const [error, setError] = useState(''); const idKey = kind === 'skill' ? 'id_skill' : 'id_language'; const create = kind === 'skill' ? createSkill : createLanguage; const update = kind === 'skill' ? updateSkill : updateLanguage; const remove = kind === 'skill' ? deleteSkill : deleteLanguage
  const add = (name) => { const value = name || ''; if (kind === 'skill' && name !== undefined && (!value.trim() || items.some((item) => normalize(item.name || '') === normalize(value)))) return false; setItems((current) => [...current, { [idKey]: 'new-' + Date.now(), name: value, level: '' }]); return true }
  const change = (id, field, value) => setItems((current) => current.map((item) => item[idKey] === id ? { ...item, [field]: value } : item))
  const save = async (item) => { setSaving(item[idKey]); setError(''); try { const result = item[idKey].startsWith('new-') ? await create(resumeId, item) : await update(resumeId, item[idKey], item); setItems((current) => current.map((entry) => entry[idKey] === item[idKey] ? result[kind] : entry)) } catch (requestError) { setError(requestError.message) } finally { setSaving('') } }
  const del = async (item) => { setError(''); try { if (!item[idKey].startsWith('new-')) await remove(resumeId, item[idKey]); setItems((current) => current.filter((entry) => entry[idKey] !== item[idKey])) } catch (requestError) { setError(requestError.message) } }
  const addAndSaveSkill = async (name) => { const value = name?.trim(); if (!value || items.some((item) => normalize(item.name || '') === normalize(value))) return false; const item = { id_skill: 'new-' + Date.now(), name: value, level: '' }; setSaving(item.id_skill); setError(''); setItems((current) => [...current, item]); try { const result = await createSkill(resumeId, item); setItems((current) => current.map((entry) => entry.id_skill === item.id_skill ? result.skill : entry)); return true } catch (requestError) { setError(requestError.message); setItems((current) => current.filter((entry) => entry.id_skill !== item.id_skill)); return false } finally { setSaving('') } }
  return <section><div className="resume-section-heading"><div><p>Profil</p><h2>{title}</h2></div>{kind !== 'skill' && <button type="button" className="section-add" onClick={() => add()}><CirclePlus size={16} /> Ajouter une langue</button>}</div>{kind === 'skill' && <SkillSelector items={items} addSkill={addAndSaveSkill} removeSkill={del} jobTitles={jobTitles} />}{error && <p className="editor-feedback editor-feedback--error" role="alert">{error}</p>}{kind !== 'skill' && items.map((item) => <TagCard key={item[idKey]} item={item} kind={kind} saving={saving === item[idKey]} isOverflow={isOverflow} onChange={(field, value) => change(item[idKey], field, value)} onSave={() => save(item)} onDelete={() => del(item)} />)}</section>
}
export default function ResumeTags(props) { return <div className="resume-sections"><TagSection title="Compétences" kind="skill" resumeId={props.resumeId} items={props.skills} setItems={props.setSkills} jobTitles={(props.experiences || []).map((item) => item.job_title).filter(Boolean)} isOverflow={props.isOverflow} /><TagSection title="Langues" kind="language" resumeId={props.resumeId} items={props.languages} setItems={props.setLanguages} isOverflow={props.isOverflow} /></div> }
