import { CirclePlus, Trash2 } from 'lucide-react'
import { useState } from 'react'
import Button from '../common/Button'
import { createLanguage, createSkill, deleteLanguage, deleteSkill, updateLanguage, updateSkill } from '../../services/resumeService'

const levels = { skill: ['Débutant', 'Intermédiaire', 'Avancé', 'Expert'], language: ['Débutant', 'Intermédiaire', 'Courant', 'Bilingue', 'Langue maternelle'] }
function TagCard({ item, kind, onChange, onSave, onDelete, saving }) { return <article className="resume-section-card tag-card"><div className="editor-field-grid"><label>{kind === 'skill' ? 'Compétence' : 'Langue'}<input value={item.name} onChange={(event) => onChange('name', event.target.value)} /></label><label>Niveau<select value={item.level} onChange={(event) => onChange('level', event.target.value)}><option value="">Sélectionner</option>{levels[kind].map((level) => <option key={level}>{level}</option>)}</select></label></div><div className="tag-card-actions"><Button type="button" onClick={onSave} disabled={saving}>{saving ? 'Enregistrement…' : 'Enregistrer'}</Button><button type="button" className="section-delete" onClick={onDelete}><Trash2 size={15} /> Supprimer</button></div></article> }
function TagSection({ title, kind, resumeId, items, setItems }) { const [saving, setSaving] = useState(''); const idKey = kind === 'skill' ? 'id_skill' : 'id_language'; const create = kind === 'skill' ? createSkill : createLanguage; const update = kind === 'skill' ? updateSkill : updateLanguage; const remove = kind === 'skill' ? deleteSkill : deleteLanguage; const add = () => setItems((current) => [...current, { [idKey]: 'new-' + Date.now(), name: '', level: '' }]); const change = (id, field, value) => setItems((current) => current.map((item) => item[idKey] === id ? { ...item, [field]: value } : item)); const save = async (item) => { setSaving(item[idKey]); try { const result = item[idKey].startsWith('new-') ? await create(resumeId, item) : await update(resumeId, item[idKey], item); setItems((current) => current.map((entry) => entry[idKey] === item[idKey] ? result[kind] : entry)) } finally { setSaving('') } }; const del = async (item) => { if (!item[idKey].startsWith('new-')) await remove(resumeId, item[idKey]); setItems((current) => current.filter((entry) => entry[idKey] !== item[idKey])) }; return <section><div className="resume-section-heading"><div><p>Profil</p><h2>{title}</h2></div><button type="button" className="section-add" onClick={add}><CirclePlus size={16} /> Ajouter une {kind === 'skill' ? 'compétence' : 'langue'}</button></div>{items.map((item) => <TagCard key={item[idKey]} item={item} kind={kind} saving={saving === item[idKey]} onChange={(field, value) => change(item[idKey], field, value)} onSave={() => save(item)} onDelete={() => del(item)} />)}</section> }
export default function ResumeTags(props) { return <div className="resume-sections"><TagSection title="Compétences" kind="skill" resumeId={props.resumeId} items={props.skills} setItems={props.setSkills} /><TagSection title="Langues" kind="language" resumeId={props.resumeId} items={props.languages} setItems={props.setLanguages} /></div> }
