import { useEffect, useState } from 'react'
import { BarChart3, Search, Trash2 } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { deleteJobAnalysis, getJobAnalyses } from '../services/jobAnalysisService'
import { useAuth } from '../store/AuthContext'

function formatDate(date) { return date ? new Intl.DateTimeFormat('fr-FR', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(date)) : '' }

export default function JobAnalysisListPage() {
  const navigate = useNavigate()
  const { user } = useAuth()
  const [analyses, setAnalyses] = useState([]); const [search, setSearch] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [selected, setSelected] = useState([])
  useEffect(() => { getJobAnalyses().then(({ job_analyses }) => setAnalyses(job_analyses)).catch((requestError) => setError(requestError.message)).finally(() => setLoading(false)) }, [])
  async function remove(item) { if (!window.confirm('Supprimer cette analyse ?')) return; try { await deleteJobAnalysis(item.id_job_analysis); setAnalyses((current) => current.filter((analysis) => analysis.id_job_analysis !== item.id_job_analysis)) } catch (requestError) { setError(requestError.message) } }
  function toggleSelection(id) { setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : current.length < 3 ? [...current, id] : current) }
  const visible = analyses.filter((item) => [item.company_name, item.job_title, item.title_resume].some((value) => value?.toLowerCase().includes(search.trim().toLowerCase())))
  return <main className="app-page job-analysis-list-page"><header className="app-header"><div><p className="crumb">Vos candidatures</p><h1>Mes analyses</h1></div><Link className="button" to="/analyse-offre">Analyser une offre</Link></header>{loading && <p className="dashboard-feedback">Chargement de vos analyses…</p>}{error && <p className="dashboard-feedback dashboard-feedback--error" role="alert">{error}</p>}{!loading && !error && analyses.length === 0 && <section className="analyses-empty"><BarChart3 size={28} /><h2>Aucune analyse enregistrée.</h2><p>Analysez une offre pour retrouver ici ses recommandations.</p><Link className="button" to="/analyse-offre">Analyser une offre</Link></section>}{!loading && analyses.length > 0 && <><label className="analysis-search"><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Rechercher une entreprise, un poste ou un CV" /></label>{user?.plan === 'pro' ? <div className="analysis-compare-toolbar"><p>Sélectionnez 2 ou 3 analyses pour une comparaison côte à côte.</p><button className="button" type="button" disabled={selected.length < 2} onClick={() => navigate('/analyses/comparer?ids=' + encodeURIComponent(selected.join(',')))}>Comparer les offres ({selected.length})</button></div> : <p className="analysis-compare-toolbar__upgrade">La comparaison côte à côte est disponible avec Novyata Pro.</p>}<section className="analysis-history" aria-label="Historique des analyses">{visible.map((item) => <article key={item.id_job_analysis}>{user?.plan === 'pro' && <label className="analysis-select"><input type="checkbox" aria-label={'Sélectionner ' + (item.company_name || item.job_title || 'cette offre')} checked={selected.includes(item.id_job_analysis)} disabled={!selected.includes(item.id_job_analysis) && selected.length >= 3} onChange={() => toggleSelection(item.id_job_analysis)} /></label>}<div><b>{item.company_name || 'Entreprise non renseignée'}</b><strong>{item.job_title || 'Poste non renseigné'}</strong><small>{item.title_resume} · {formatDate(item.updated_at)}</small></div><span>{item.match_score}%</span><Link to={'/analyses/' + item.id_job_analysis}>Voir</Link><button type="button" aria-label={'Supprimer l’analyse ' + (item.company_name || item.job_title)} onClick={() => remove(item)}><Trash2 size={16} /></button></article>)}{visible.length === 0 && <p className="analysis-empty">Aucune analyse ne correspond à votre recherche.</p>}</section></>}</main>
}
