import { useEffect, useState } from 'react'
import { CheckCircle2, FileSearch, Lightbulb, ScanSearch, WandSparkles } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import Button from '../components/common/Button'
import CoverLetterPreview, { letterCharacterCount, letterWordCount } from '../components/coverLetters/CoverLetterPreview'
import { createCoverLetter } from '../services/coverLetterService'
import { generateCoverLetter } from '../services/coverLetterGenerationService'
import { applyCvAdaptation, getCvAdaptationProposals } from '../services/cvAdaptationService'
import { getJobAnalysis } from '../services/jobAnalysisService'
import { getResume } from '../services/resumeService'
import { useAuth } from '../store/AuthContext'

function MatchList({ items = [] }) { return items.length ? <ul className="analysis-detail-list">{items.map(({ name, evidence, reason }) => <li key={name}><strong>{name}</strong><span>{reason}</span><em>Preuve : « {evidence} »</em></li>)}</ul> : <p className="analysis-empty">Aucun élément identifié.</p> }
function MissingList({ items = [] }) { return items.length ? <ul className="analysis-detail-list">{items.map(({ name, reason }) => <li key={name}><strong>{name}</strong><span>{reason}</span></li>)}</ul> : <p className="analysis-empty">Aucun élément identifié.</p> }
function letterTitle(company, job) { return company ? `Candidature — ${company}` : job ? `Candidature — ${job}` : 'Lettre de motivation' }

export default function JobAnalysisDetailPage() {
  const { id } = useParams(); const navigate = useNavigate(); const { user } = useAuth()
  const [item, setItem] = useState(null); const [resume, setResume] = useState(null); const [generation, setGeneration] = useState(null); const [adaptation, setAdaptation] = useState(null); const [acceptedIds, setAcceptedIds] = useState(new Set()); const [loading, setLoading] = useState(true); const [generating, setGenerating] = useState(false); const [adapting, setAdapting] = useState(false); const [applying, setApplying] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState('')

  useEffect(() => { getJobAnalysis(id).then(async ({ job_analysis }) => { setItem(job_analysis); const result = await getResume(job_analysis.id_resume); setResume(result.resume) }).catch((requestError) => setError(requestError.message)).finally(() => setLoading(false)) }, [id])
  async function generate() { if (!item) return; setGenerating(true); setError(''); try { const result = await generateCoverLetter({ resumeId: item.id_resume, jobDescription: item.job_description, companyName: item.company_name, jobTitle: item.job_title, analysis: item.analysis }); setGeneration(result.generation) } catch (requestError) { setError(requestError.message) } finally { setGenerating(false) } }
  async function saveLetter() { if (!generation || !item) return; setSaving(true); setError(''); try { const { cover_letter } = await createCoverLetter({ title: letterTitle(item.company_name, item.job_title), company_name: item.company_name || null, job_title: item.job_title || null, recipient_name: null, recipient_position: null, company_address: null, subject: generation.subject, content: generation.content, id_resume: item.id_resume, template: 'classic' }); navigate('/lettres/' + cover_letter.id_cover_letter) } catch (requestError) { setError(requestError.message) } finally { setSaving(false) } }
  async function adapt() { setAdapting(true); setError(''); try { const result = await getCvAdaptationProposals(id); setAdaptation(result.adaptation); setAcceptedIds(new Set()) } catch (requestError) { setError(requestError.message) } finally { setAdapting(false) } }
  function toggleProposal(proposalId) { setAcceptedIds((current) => { const next = new Set(current); next.has(proposalId) ? next.delete(proposalId) : next.add(proposalId); return next }) }
  function acceptAll() { if (!adaptation?.proposals.length || !window.confirm('Accepter toutes les propositions et créer une copie de votre CV ?')) return; setAcceptedIds(new Set(adaptation.proposals.map((proposal) => proposal.id))) }
  function ignoreAll() { setAcceptedIds(new Set()) }
  async function applyAdaptation() { if (!adaptation || acceptedIds.size === 0) return; setApplying(true); setError(''); try { const result = await applyCvAdaptation(id, { proposals: adaptation.proposals, acceptedIds: [...acceptedIds] }); navigate('/cv/' + result.resume.id_resume) } catch (requestError) { setError(requestError.message) } finally { setApplying(false) } }

  if (loading) return <main className="app-page"><p className="dashboard-feedback">Chargement de l’analyse…</p></main>
  if (error && !item) return <main className="app-page"><p className="dashboard-feedback dashboard-feedback--error" role="alert">{error}</p></main>
  const analysis = item.analysis
  return <main className="app-page job-analysis-page"><header className="app-header"><div><p className="crumb">Analyse enregistrée</p><h1>{item.company_name || item.job_title || 'Analyse d’offre'}</h1></div><Link className="button" to="/analyses">Retour aux analyses</Link></header>{error && <p className="editor-feedback editor-feedback--error" role="alert">{error}</p>}<section className="analysis-results"><header><div><p>Résultat enregistré</p><h2>Correspondance estimée</h2><span className="analysis-score-explanation">{analysis.scoreExplanation}</span></div><strong>{analysis.matchScore}<small>%</small></strong></header><div className="analysis-result-grid"><article><h3><CheckCircle2 size={17} /> Correspondances solides</h3><MatchList items={analysis.strongMatches} /></article><article><h3><FileSearch size={17} /> Présentes mais à préciser</h3><MatchList items={analysis.partialMatches} /></article><article><h3><ScanSearch size={17} /> Manques importants</h3><MissingList items={analysis.importantMissingSkills} /></article><article><h3><Lightbulb size={17} /> Bonus manquants</h3><MissingList items={analysis.optionalMissingSkills} /></article><article><h3><ScanSearch size={17} /> Mots-clés importants</h3><div className="analysis-tags">{analysis.importantKeywords.map((keyword) => <span key={keyword}>{keyword}</span>)}</div></article><article><h3><Lightbulb size={17} /> Suggestions prioritaires</h3><ul>{analysis.suggestions.map((suggestion) => <li key={suggestion}>{suggestion}</li>)}</ul></article></div><p className="analysis-safety-note">{analysis.safetyNote || 'N’ajoutez une compétence à votre CV que si vous la maîtrisez réellement.'}</p><div className="analysis-generation-action"><div><h3>Une lettre adaptée à cette offre</h3><p>Générez un brouillon à partir de cette analyse sauvegardée.</p></div><Button type="button" onClick={generate} disabled={generating}>{generating ? 'Génération…' : 'Générer une lettre de motivation'}</Button></div></section>
    <section className="cv-adaptation-section"><header><div><p className="crumb">Copie sécurisée</p><h2>Adapter mon CV à cette offre</h2><p>Votre CV original restera inchangé. Vous choisissez chaque reformulation avant la création de la copie.</p></div>{!adaptation && <Button type="button" onClick={adapt} disabled={adapting}><WandSparkles size={16} />{adapting ? 'Préparation…' : 'Adapter mon CV à cette offre'}</Button>}</header>{adaptation && <>{adaptation.proposals.length === 0 ? <p className="analysis-empty">Aucune reformulation pertinente n’a été proposée pour ce CV.</p> : <><div className="adaptation-actions"><span>{acceptedIds.size} modification{acceptedIds.size > 1 ? 's' : ''} sélectionnée{acceptedIds.size > 1 ? 's' : ''}</span><Button type="button" variant="secondary" onClick={acceptAll}>Tout accepter</Button><Button type="button" variant="secondary" onClick={ignoreAll}>Tout ignorer</Button></div><div className="adaptation-proposals">{adaptation.proposals.map((proposal, index) => { const accepted = acceptedIds.has(proposal.id); return <article key={proposal.id} className={accepted ? 'is-accepted' : ''}><header><span>Proposition {index + 1}</span><small>{proposal.reason}</small></header><div><p>Texte actuel</p><blockquote>{proposal.currentText}</blockquote></div><div><p>Proposition</p><blockquote>{proposal.proposedText}</blockquote></div><Button type="button" variant={accepted ? 'secondary' : 'primary'} onClick={() => toggleProposal(proposal.id)}>{accepted ? 'Ignorer' : 'Accepter'}</Button></article> })}</div><div className="adaptation-apply"><p>Une copie du CV sera créée avec uniquement les modifications sélectionnées.</p><Button type="button" onClick={applyAdaptation} disabled={applying || acceptedIds.size === 0}>{applying ? 'Création de la copie…' : `Créer mon CV adapté (${acceptedIds.size})`}</Button></div></>}</>}</section>
    {generation && <section className="generated-letter-section"><h2>Relisez votre lettre avant de l’enregistrer.</h2><div className="generated-letter-layout"><div className="generated-letter-form"><label>Objet<input aria-label="Objet de la lettre" value={generation.subject} onChange={(event) => setGeneration((current) => ({ ...current, subject: event.target.value }))} /></label><label>Contenu<textarea aria-label="Contenu de la lettre" value={generation.content} onChange={(event) => setGeneration((current) => ({ ...current, content: event.target.value }))} rows="16" /><small>{letterWordCount(generation.content)} mots · {letterCharacterCount(generation.content)} caractères</small></label><Button type="button" onClick={saveLetter} disabled={saving}>{saving ? 'Enregistrement…' : 'Enregistrer dans mes lettres'}</Button></div><aside><p className="resume-preview-label">Aperçu A4 en direct</p><CoverLetterPreview letter={{ subject: generation.subject, content: generation.content, company_name: item.company_name, job_title: item.job_title, template: 'classic' }} resume={resume} user={user} /></aside></div></section>}</main>
}
