import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import Button from '../components/common/Button'
import { changePassword, deleteAccount, updateProfile } from '../services/authService'
import { useAuth } from '../store/AuthContext'

export default function SettingsPage() {
  const { user, setUser, theme, setTheme, logout } = useAuth(); const navigate = useNavigate(); const [profile, setProfile] = useState(() => ({ first_name: user.first_name, last_name: user.last_name, email: user.email })); const [passwords, setPasswords] = useState({ current_password: '', new_password: '', confirmation: '' }); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [deleting, setDeleting] = useState(false)
  const notice = (fn) => async (event) => { event.preventDefault(); setError(''); setMessage(''); try { await fn(); setMessage('Modifications enregistrées.') } catch (requestError) { setError(requestError.message) } }
  const saveProfile = notice(async () => { const { user: updated } = await updateProfile(profile); setUser(updated) })
  const savePassword = notice(async () => { await changePassword(passwords); setPasswords({ current_password: '', new_password: '', confirmation: '' }) })
  async function remove() { if (!window.confirm('Supprimer définitivement votre compte et toutes vos données ?')) return; setDeleting(true); setError(''); try { await deleteAccount(); logout(); navigate('/') } catch (requestError) { setError(requestError.message); setDeleting(false) } }
  return <main className="app-page settings-page"><header className="app-header"><div><p className="crumb">Compte</p><h1>Paramètres</h1></div></header>{message && <p className="editor-feedback" role="status">{message}</p>}{error && <p className="editor-feedback editor-feedback--error" role="alert">{error}</p>}<section className="settings-card"><div><p>Profil</p><h2>Vos informations</h2></div><form onSubmit={saveProfile}><div className="editor-field-grid"><label>Prénom<input value={profile.first_name} onChange={(e) => setProfile({ ...profile, first_name: e.target.value })} /></label><label>Nom<input value={profile.last_name} onChange={(e) => setProfile({ ...profile, last_name: e.target.value })} /></label></div><label>Email<input type="email" value={profile.email} onChange={(e) => setProfile({ ...profile, email: e.target.value })} /></label><Button>Enregistrer les modifications</Button></form></section><section className="settings-card"><div><p>Sécurité</p><h2>Modifier le mot de passe</h2></div><form onSubmit={savePassword}>{[['current_password', 'Mot de passe actuel'], ['new_password', 'Nouveau mot de passe'], ['confirmation', 'Confirmation du nouveau mot de passe']].map(([key, label]) => <label key={key}>{label}<input type="password" value={passwords[key]} onChange={(e) => setPasswords({ ...passwords, [key]: e.target.value })} /></label>)}<Button>Modifier le mot de passe</Button></form></section><section className="settings-card"><div><p>Préférences</p><h2>Interface</h2></div><div className="settings-preferences"><label>Thème<select value={theme} onChange={(event) => setTheme(event.target.value)}><option value="light">Clair</option><option value="dark">Sombre</option><option value="system">Système</option></select></label><label>Format de date<input value="JJ/MM/AAAA" readOnly /></label><label>Langue<input value="Français" readOnly /></label></div></section><section className="settings-card settings-card--danger"><div><p>Zone danger</p><h2>Supprimer mon compte</h2><span>Cette action est définitive. Tous vos CV et vos données seront supprimés.</span></div><Button type="button" variant="danger" disabled={deleting} onClick={remove}>{deleting ? 'Suppression…' : 'Supprimer mon compte'}</Button></section></main>
}
