import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import Button from '../components/common/Button'
import { changePassword, deleteAccount, resendVerification, updateProfile } from '../services/authService'
import { openCustomerPortal, startProCheckout } from '../services/billingService'
import { getUsage } from '../services/usageService'
import { useAuth } from '../store/AuthContext'

const labels = { job_analysis: 'Analyse d’offres', cover_letter_generation: 'Lettres IA', cv_adaptation: 'Adaptations CV' }
export default function SettingsPage() {
  const { user, setUser, theme, setTheme, logout } = useAuth(); const navigate = useNavigate(); const [profile, setProfile] = useState(() => ({ first_name: user.first_name, last_name: user.last_name, email: user.email })); const [passwords, setPasswords] = useState({ current_password: '', new_password: '', confirmation: '' }); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [deleting, setDeleting] = useState(false); const [usage, setUsage] = useState(null); const [billingLoading, setBillingLoading] = useState(false)
  useEffect(() => { getUsage().then(({ usage: result }) => setUsage(result)).catch(() => {}) }, [])
  const notice = (fn) => async (event) => { event.preventDefault(); setError(''); setMessage(''); try { await fn(); setMessage('Modifications enregistrées.') } catch (requestError) { setError(requestError.message) } }
  const saveProfile = notice(async () => { const { user: updated } = await updateProfile(profile); setUser(updated) }); const savePassword = notice(async () => { await changePassword(passwords); setPasswords({ current_password: '', new_password: '', confirmation: '' }) })
  async function remove() { if (!window.confirm('Supprimer définitivement votre compte et toutes vos données ?')) return; setDeleting(true); setError(''); try { await deleteAccount(); logout(); navigate('/') } catch (requestError) { setError(requestError.message); setDeleting(false) } }
  async function billing(action) { setBillingLoading(true); setError(''); try { const { url } = await action(); window.location.assign(url) } catch (requestError) { setError(requestError.message); setBillingLoading(false) } }
  return <main className="app-page settings-page"><header className="app-header"><div><p className="crumb">Compte</p><h1>Paramètres</h1></div></header>{message && <p className="editor-feedback" role="status">{message}</p>}{error && <p className="editor-feedback editor-feedback--error" role="alert">{error}</p>}
    <section className="settings-card"><div><p>Abonnement</p><h2>{user.plan === 'pro' ? 'Novyata Pro' : 'Novyata Free'}</h2><span>{user.plan === 'pro' ? `Statut : ${user.subscription_status || 'actif'}${user.current_period_end ? ` · prochaine échéance ${new Date(user.current_period_end).toLocaleDateString('fr-FR')}` : ''}` : 'Le plan gratuit inclut la création de CV, les exports PDF, les candidatures et des usages IA mensuels.'}</span></div><Button type="button" disabled={billingLoading} onClick={() => billing(user.plan === 'pro' ? openCustomerPortal : startProCheckout)}>{billingLoading ? 'Redirection…' : user.plan === 'pro' ? 'Gérer mon abonnement' : 'Passer à Pro'}</Button></section>
    <section className="settings-card"><div><p>Utilisation ce mois-ci</p><h2>Fonctionnalités IA</h2></div>{usage ? <div className="usage-grid">{usage.features.map((feature) => <article key={feature.feature}><b>{labels[feature.feature]}</b><span>{feature.used} / {feature.limit} utilisées</span><div><i style={{ width: `${Math.min(100, feature.used / feature.limit * 100)}%` }} /></div>{feature.remaining === 0 && <Link to="/pro">Découvrir Novyata Pro</Link>}</article>)}</div> : <span>Chargement de votre utilisation…</span>}</section>
    {!user.email_verified && <section className="settings-card"><div><p>Sécurité</p><h2>Adresse e-mail non vérifiée</h2><span>Vérifiez votre adresse pour renforcer la sécurité de votre compte.</span></div><Button type="button" variant="secondary" onClick={() => resendVerification().then(() => setMessage('E-mail de vérification renvoyé.')).catch((requestError) => setError(requestError.message))}>Renvoyer l’e-mail de vérification</Button></section>}
    <section className="settings-card"><div><p>Profil</p><h2>Vos informations</h2></div><form onSubmit={saveProfile}><div className="editor-field-grid"><label>Prénom<input value={profile.first_name} onChange={(e) => setProfile({ ...profile, first_name: e.target.value })} /></label><label>Nom<input value={profile.last_name} onChange={(e) => setProfile({ ...profile, last_name: e.target.value })} /></label></div><label>Email<input type="email" value={profile.email} onChange={(e) => setProfile({ ...profile, email: e.target.value })} /></label><Button>Enregistrer les modifications</Button></form></section>
    <section className="settings-card"><div><p>Sécurité</p><h2>Modifier le mot de passe</h2></div><form onSubmit={savePassword}>{[['current_password', 'Mot de passe actuel'], ['new_password', 'Nouveau mot de passe'], ['confirmation', 'Confirmation du nouveau mot de passe']].map(([key, label]) => <label key={key}>{label}<input type="password" value={passwords[key]} onChange={(e) => setPasswords({ ...passwords, [key]: e.target.value })} /></label>)}<Button>Modifier le mot de passe</Button></form></section>
    <section className="settings-card"><div><p>Préférences</p><h2>Interface</h2></div><div className="settings-preferences"><label>Thème<select value={theme} onChange={(event) => setTheme(event.target.value)}><option value="light">Clair</option><option value="dark">Sombre</option><option value="system">Système</option></select></label><label>Format de date<input value="JJ/MM/AAAA" readOnly /></label><label>Langue<input value="Français" readOnly /></label></div></section>
    <section className="settings-card settings-card--danger"><div><p>Zone danger</p><h2>Supprimer mon compte</h2><span>Cette action est définitive. Tous vos CV et vos données seront supprimés.</span></div><Button type="button" variant="danger" disabled={deleting} onClick={remove}>{deleting ? 'Suppression…' : 'Supprimer mon compte'}</Button></section></main>
}
