import { useEffect, useState } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import Button from '../components/common/Button'
import { changePassword, deleteAccount, getCurrentUser, resendVerification, updateProfile, updateSearchPreferences } from '../services/authService'
import { openCustomerPortal, startProCheckout } from '../services/billingService'
import { getUsage } from '../services/usageService'
import { useAuth } from '../store/AuthContext'

const labels = { job_analysis: 'Analyse d’offres', cover_letter_generation: 'Lettres IA', cv_adaptation: 'Adaptations CV', application_followup: 'Relances IA', interview_preparation: 'Préparation entretien', interview_simulation: 'Simulation entretien' }
export default function SettingsPage() {
  const { user, setUser, theme, setTheme, logout } = useAuth(); const navigate = useNavigate(); const [searchParams, setSearchParams] = useSearchParams(); const [profile, setProfile] = useState(() => ({ first_name: user.first_name, last_name: user.last_name, email: user.email })); const [searchPreferences, setSearchPreferences] = useState(() => user.job_search_preferences || {}); const [passwords, setPasswords] = useState({ current_password: '', new_password: '', confirmation: '' }); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [deleting, setDeleting] = useState(false); const [usage, setUsage] = useState(null); const [billingLoading, setBillingLoading] = useState(false); const [billingRefreshPending, setBillingRefreshPending] = useState(false)
  useEffect(() => { getUsage().then(({ usage: result }) => setUsage(result)).catch(() => {}) }, [])
  async function refreshBillingStatus(waitForWebhook = false) {
    setBillingLoading(true); setError('')
    try {
      const attempts = waitForWebhook ? 6 : 1
      for (let attempt = 0; attempt < attempts; attempt += 1) {
        const { user: refreshed } = await getCurrentUser(localStorage.getItem('novyata_auth_token'))
        setUser(refreshed)
        if (refreshed.plan === 'pro') { setBillingRefreshPending(false); setMessage('Votre abonnement Novyata Pro est actif.'); setBillingLoading(false); return }
        if (attempt + 1 < attempts) await new Promise((resolve) => window.setTimeout(resolve, 1000))
      }
      setBillingRefreshPending(true); setMessage('Le retour de Checkout est reçu. L’activation apparaîtra dès que le webhook Stripe aura confirmé le paiement.')
    } catch (requestError) { setError(requestError.message) } finally { setBillingLoading(false) }
  }
  useEffect(() => {
    const checkout = searchParams.get('checkout')
    if (!checkout) return
    if (checkout === 'success') refreshBillingStatus(true)
    if (checkout === 'cancelled') setMessage('Checkout annulé. Aucun changement d’abonnement n’a été effectué.')
    setSearchParams((current) => { current.delete('checkout'); return current }, { replace: true })
  }, [searchParams, setSearchParams])
  const notice = (fn) => async (event) => { event.preventDefault(); setError(''); setMessage(''); try { await fn(); setMessage('Modifications enregistrées.') } catch (requestError) { setError(requestError.message) } }
  const saveProfile = notice(async () => { const { user: updated } = await updateProfile(profile); setUser(updated) }); const savePassword = notice(async () => { await changePassword(passwords); setPasswords({ current_password: '', new_password: '', confirmation: '' }) })
  const saveSearchPreferences = notice(async () => { const { user: updated } = await updateSearchPreferences(searchPreferences); setUser(updated); setSearchPreferences(updated.job_search_preferences || {}) })
  async function remove() { if (!window.confirm('Supprimer définitivement votre compte et toutes vos données ?')) return; setDeleting(true); setError(''); try { await deleteAccount(); logout(); navigate('/') } catch (requestError) { setError(requestError.message); setDeleting(false) } }
  async function billing(action) { setBillingLoading(true); setError(''); try { const { url } = await action(); window.location.assign(url) } catch (requestError) { setError(requestError.message); setBillingLoading(false) } }
  return <main className="app-page settings-page"><header className="app-header"><div><p className="crumb">Compte</p><h1>Paramètres</h1></div></header>{message && <p className="editor-feedback" role="status">{message}</p>}{error && <p className="editor-feedback editor-feedback--error" role="alert">{error}</p>}
    <section className="settings-card"><div><p>Abonnement</p><h2>{user.plan === 'pro' ? 'Novyata Pro' : 'Novyata Free'}</h2><span>{user.plan === 'pro' ? `Statut : ${user.subscription_status || 'actif'}${user.current_period_end ? ` · prochaine échéance ${new Date(user.current_period_end).toLocaleDateString('fr-FR')}` : ''}` : 'Le plan gratuit inclut la création de CV, les exports PDF, les candidatures et des usages IA mensuels.'}</span></div><div className="settings-billing-actions"><Button type="button" disabled={billingLoading} onClick={() => billing(user.plan === 'pro' ? openCustomerPortal : startProCheckout)}>{billingLoading ? 'Vérification…' : user.plan === 'pro' ? 'Gérer mon abonnement' : 'Passer à Pro'}</Button>{billingRefreshPending && <Button type="button" variant="secondary" disabled={billingLoading} onClick={() => refreshBillingStatus(false)}>Actualiser l’abonnement</Button>}</div></section>
    <section className="settings-card"><div><p>Utilisation ce mois-ci</p><h2>Fonctionnalités IA</h2></div>{usage ? <div className="usage-grid">{usage.features.map((feature) => <article key={feature.feature}><b>{labels[feature.feature] || feature.feature}</b><span>{feature.limit ? `${feature.used} / ${feature.limit} utilisées` : 'Disponible avec Novyata Pro'}</span>{Boolean(feature.limit) && <div><i style={{ width: `${Math.min(100, feature.used / feature.limit * 100)}%` }} /></div>}{feature.remaining === 0 && <Link to="/tarifs">Découvrir Novyata Pro</Link>}</article>)}</div> : <span>Chargement de votre utilisation…</span>}</section>
    {!user.email_verified && <section className="settings-card"><div><p>Sécurité</p><h2>Adresse e-mail non vérifiée</h2><span>Vérifiez votre adresse pour renforcer la sécurité de votre compte.</span></div><Button type="button" variant="secondary" onClick={() => resendVerification().then(() => setMessage('E-mail de vérification renvoyé.')).catch((requestError) => setError(requestError.message))}>Renvoyer l’e-mail de vérification</Button></section>}
    <section className="settings-card"><div><p>Profil</p><h2>Vos informations</h2></div><form onSubmit={saveProfile}><div className="editor-field-grid"><label>Prénom<input value={profile.first_name} onChange={(e) => setProfile({ ...profile, first_name: e.target.value })} /></label><label>Nom<input value={profile.last_name} onChange={(e) => setProfile({ ...profile, last_name: e.target.value })} /></label></div><label>Email<input type="email" value={profile.email} onChange={(e) => setProfile({ ...profile, email: e.target.value })} /></label><Button>Enregistrer les modifications</Button></form></section>
    <section className="settings-card"><div><p>Ma recherche</p><h2>Préférences de recherche</h2><span>Ces informations pourront préremplir vos prochains outils sans modifier vos CV.</span></div><form onSubmit={saveSearchPreferences}><div className="editor-field-grid"><label>Métiers recherchés<input value={searchPreferences.roles || ''} onChange={(e) => setSearchPreferences({ ...searchPreferences, roles: e.target.value })} placeholder="Ex. Product designer, UX designer" /></label><label>Localisation souhaitée<input value={searchPreferences.location || ''} onChange={(e) => setSearchPreferences({ ...searchPreferences, location: e.target.value })} /></label></div><div className="editor-field-grid"><label>Type de contrat<input value={searchPreferences.contract_type || ''} onChange={(e) => setSearchPreferences({ ...searchPreferences, contract_type: e.target.value })} placeholder="CDI, alternance…" /></label><label>Télétravail<input value={searchPreferences.remote_work || ''} onChange={(e) => setSearchPreferences({ ...searchPreferences, remote_work: e.target.value })} placeholder="Hybride, à distance…" /></label></div><div className="editor-field-grid"><label>Disponibilité<input value={searchPreferences.availability || ''} onChange={(e) => setSearchPreferences({ ...searchPreferences, availability: e.target.value })} /></label><label>Salaire souhaité<input value={searchPreferences.salary || ''} onChange={(e) => setSearchPreferences({ ...searchPreferences, salary: e.target.value })} /></label></div><label>Secteurs préférés<input value={searchPreferences.sectors || ''} onChange={(e) => setSearchPreferences({ ...searchPreferences, sectors: e.target.value })} /></label><Button>Enregistrer ma recherche</Button></form></section>
    <section className="settings-card"><div><p>Sécurité</p><h2>Modifier le mot de passe</h2></div><form onSubmit={savePassword}>{[['current_password', 'Mot de passe actuel'], ['new_password', 'Nouveau mot de passe'], ['confirmation', 'Confirmation du nouveau mot de passe']].map(([key, label]) => <label key={key}>{label}<input type="password" value={passwords[key]} onChange={(e) => setPasswords({ ...passwords, [key]: e.target.value })} /></label>)}<Button>Modifier le mot de passe</Button></form></section>
    <section className="settings-card"><div><p>Préférences</p><h2>Interface</h2></div><div className="settings-preferences"><label>Thème<select value={theme} onChange={(event) => setTheme(event.target.value)}><option value="light">Clair</option><option value="dark">Sombre</option><option value="system">Système</option></select></label><label>Format de date<input value="JJ/MM/AAAA" readOnly /></label><label>Langue<input value="Français" readOnly /></label></div></section>
    <section className="settings-card settings-card--danger"><div><p>Zone danger</p><h2>Supprimer mon compte</h2><span>Cette action est définitive. Tous vos CV et vos données seront supprimés.</span></div><Button type="button" variant="danger" disabled={deleting} onClick={remove}>{deleting ? 'Suppression…' : 'Supprimer mon compte'}</Button></section></main>
}
